import { assert, assertEquals } from "jsr:@std/assert";
import { canTransitionZodianExpansionCohortIdentityV1, getZodianCanonicalIdentityExpansionCohort24V1, listZodianCanonicalIdentityExpansionCohort24V1, listZodianCanonicalIdentityExpansionCohort24V1BlindEntries, listZodianCanonicalIdentityExpansionWave, listZodianCanonicalIdentityExpansionWaveBBlindEntries, validateZodianCanonicalIdentityExpansionCohort24V1, validateZodianExpansionCohortIdentityCandidateV1, ZODIAN_CANONICAL_IDENTITY_EXPANSION_COHORT_24_V1_BLIND_ENTRIES, ZODIAN_CANONICAL_IDENTITY_EXPANSION_COHORT_24_V1_WAVE_B_BLIND_ENTRIES, ZODIAN_CANONICAL_IDENTITY_EXPANSION_SOURCE_ID } from "./zodian-canonical-identity-expansion-cohort-24-v1.ts";
import { validateZodianIdentityEditorialProfile } from "./zodian-identity-editorial-layer-v1.ts";
import { ZODIAN_CANONICAL_IDENTITY_COHORT_12_V1_FINGERPRINT } from "./zodian-canonical-identity-cohort-12-v1-freeze.ts";
import { ZODIAN_CANONICAL_IDENTITY_COHORT_12_V2_FINGERPRINT } from "./zodian-canonical-identity-cohort-12-v2-freeze.ts";
import { ZODIAN_SHADOW_NATURAL_READER_WRITER_V1_FINGERPRINT } from "./zodian-shadow-natural-reader-writer-v1-freeze.ts";

const fields = ["coreMotivations", "recurringStrengths", "recurringFriction", "commonBlindSpots", "interpersonalPatterns", "emotionalPatterns"] as const;
Deno.test("Wave A completion, Wave B isolation, contract, and reference freezes are explicit", async () => {
  const all = listZodianCanonicalIdentityExpansionCohort24V1(), waveA = listZodianCanonicalIdentityExpansionWave("A"), waveB = listZodianCanonicalIdentityExpansionWave("B");
  assertEquals(all.length, 24); assertEquals(waveA.length, 12); assertEquals(waveB.length, 12); assertEquals(validateZodianCanonicalIdentityExpansionCohort24V1(), []);
  assert(waveA.every((entry) => entry.status === "approved" && entry.approvalEvidence && entry.profile)); assert(waveB.every((entry) => entry.status === "approved" && entry.profile && entry.approvalEvidence === "wave-b-final-source-support-blind-and-usefulness-review" && entry.reviewEvidence?.sourceSupportReviewed && entry.reviewEvidence?.fieldResponsibilityReviewed && entry.reviewEvidence?.contradictionReviewed && entry.reviewEvidence?.difficultTraitsReviewed && entry.reviewEvidence?.blindLabelReviewComplete && entry.reviewEvidence?.storyEngineUsefulnessReviewed && entry.reviewEvidence?.humanApprovalComplete)); assertEquals(waveB.filter((entry) => entry.status === "editorial_review" || entry.status === "source_ready" || entry.status === "blocked").length, 0);
  for (const entry of waveB) { const p = entry.profile!; assertEquals(validateZodianIdentityEditorialProfile(p), []); assertEquals(p.identity, entry.identity); assertEquals(p.provenance?.sourceIds, [ZODIAN_CANONICAL_IDENTITY_EXPANSION_SOURCE_ID]); for (const field of fields) assert(p[field].length >= 1 && p[field].length <= 4); }
  for (const entry of waveA) { const p = entry.profile!; assertEquals(validateZodianIdentityEditorialProfile(p), []); assertEquals(p.identity, entry.identity); assertEquals(p.provenance?.sourceIds, [ZODIAN_CANONICAL_IDENTITY_EXPANSION_SOURCE_ID]); for (const field of fields) assert(p[field].length >= 1 && p[field].length <= 4); }
  const waveBShapes = waveB.map((entry) => fields.map((field) => entry.profile![field].length).join("/")); assert(new Set(waveBShapes).size > 1); assert(!waveBShapes.every((shape) => shape === "1/1/1/1/1/1")); assert(!waveBShapes.every((shape) => shape === "2/2/2/2/2/2"));
  const noteShapes = waveA.map((entry) => fields.map((field) => entry.profile![field].length).join("/")); assert(new Set(noteShapes).size > 1); assert(!noteShapes.every((shape) => shape === "1/1/1/1/1/1")); assert(!noteShapes.every((shape) => shape === "2/2/2/2/2/2"));
  const removed = ["difficult undertakings", "striking personal presence", "obligation", "receptive setting", "plan feels exposed", "Intensity can rise before uncertainty is tolerated", "quick social observation", "moving close to another person's decisions"]; const notes = waveA.flatMap((entry) => fields.flatMap((field) => entry.profile![field])); for (const phrase of removed) assert(!notes.some((note) => note.includes(phrase)));
  assertEquals(ZODIAN_CANONICAL_IDENTITY_COHORT_12_V1_FINGERPRINT, "85cc707e80e9911edfeef448d01e7a8da2a0c3cb48bedf3a45958e0c17dcfb0f"); assertEquals(ZODIAN_CANONICAL_IDENTITY_COHORT_12_V2_FINGERPRINT, "71a508e53c50a91021234d35bc366d68edd2be9a9af701d024c2f79267c74994"); assertEquals(ZODIAN_SHADOW_NATURAL_READER_WRITER_V1_FINGERPRINT, "77e1b08cc156abbfe2e16753fddd35e1e10422fbb0e391fc21ea3133500b5c20");
  const before = getZodianCanonicalIdentityExpansionCohort24V1("Aries", "Tiger")!; before.profile!.coreMotivations[0] = "changed"; assert(getZodianCanonicalIdentityExpansionCohort24V1("Aries", "Tiger")!.profile!.coreMotivations[0] !== "changed"); assertEquals(getZodianCanonicalIdentityExpansionCohort24V1("Unknown", "Unknown"), undefined);
  assertEquals(ZODIAN_CANONICAL_IDENTITY_EXPANSION_COHORT_24_V1_BLIND_ENTRIES.length, 12); assertEquals(new Set(ZODIAN_CANONICAL_IDENTITY_EXPANSION_COHORT_24_V1_BLIND_ENTRIES).size, 12); const blindEntries = listZodianCanonicalIdentityExpansionCohort24V1BlindEntries(); assertEquals(blindEntries.length, 12); for (const entry of blindEntries) for (const field of fields) assert(entry[field].length > 0);
  assertEquals(ZODIAN_CANONICAL_IDENTITY_EXPANSION_COHORT_24_V1_WAVE_B_BLIND_ENTRIES.length, 12); assertEquals(new Set(ZODIAN_CANONICAL_IDENTITY_EXPANSION_COHORT_24_V1_WAVE_B_BLIND_ENTRIES).size, 12); const waveBBlindEntries = listZodianCanonicalIdentityExpansionWaveBBlindEntries(); assertEquals(waveBBlindEntries.length, 12); for (const entry of waveBBlindEntries) for (const field of fields) assert(entry[field].length > 0);
  const review = await Deno.readTextFile(new URL("../../../docs/editorial/ZODIAN_CANONICAL_IDENTITY_EXPANSION_COHORT_24_V1_REVIEW.md", import.meta.url)); assert(review.includes("wave-a-final-source-support-blind-and-usefulness-review")); const blindPayload = JSON.stringify(blindEntries); for (const word of ["Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo", "source:"]) assert(!blindPayload.includes(word));
  const waveBBlindPayload = JSON.stringify(waveBBlindEntries); for (const word of ["Aquarius", "Pisces", "Libra", "Scorpio", "Sagittarius", "Capricorn", "source:"]) assert(!waveBBlindPayload.includes(word));
  for (const [westernSign, chineseSign] of [["Libra", "Ox"], ["Libra", "Dragon"], ["Scorpio", "Rat"]]) { const source = await Deno.readTextFile(new URL("./zodian-canonical-identity-expansion-cohort-24-v1.ts", import.meta.url)); const baseline = new TextDecoder().decode((await new Deno.Command("git", { args: ["show", "2bc92d6024b2cdc504962e51d989b2d44bac7898:supabase/functions/_shared/zodian-canonical-identity-expansion-cohort-24-v1.ts"] }).output()).stdout); const record = source.split("\n").find((line) => line.includes(`R("${westernSign}", "${chineseSign}"`))!; assert(baseline.includes(record)); }
  const revisedNotes = waveB.flatMap((entry) => fields.flatMap((field) => entry.profile![field])); for (const phrase of ["Brings generosity and endurance to intense attachments.", "Desire and disappointment can become jealousy or brooding.", "Restlessness rises when routine feels like confinement.", "Idealistic momentum competes with pride and excess.", "Invites others into expansive plans but resists correction or restraint.", "Wants order, authority, and freedom from petty control.", "Combines patience with forceful persistence.", "Appears proper until pressure brings a direct challenge to control.", "Wants advancement, independence, and a life arranged on chosen terms.", "May assume a clever arrangement is fair because it is efficient.", "Combines generosity with persistence and broad imagination.", "May deny how strongly a slight or challenge has landed.", "Pride and uncertainty can produce emotional storms or abrupt withdrawal."]) assert(!revisedNotes.includes(phrase)); assert(!all.some((entry) => entry.identity.chineseSign === "Sheep"));
});

Deno.test("Wave A audit tripwires catch bounded invalid mutations", () => {
  const entries = listZodianCanonicalIdentityExpansionCohort24V1(); const waveA = entries.find((e) => e.wave === "A")!; waveA.profile!.coreMotivations[0] = "natural leader"; assert(validateZodianCanonicalIdentityExpansionCohort24V1(entries).some((f) => f.code === "generic_tripwire"));
  const duplicate = listZodianCanonicalIdentityExpansionCohort24V1(); duplicate[1]!.profile!.recurringStrengths[0] = duplicate[0]!.profile!.recurringStrengths[0]!; assert(validateZodianCanonicalIdentityExpansionCohort24V1(duplicate).some((f) => f.code === "normalized_duplicate"));
  const leaked = listZodianCanonicalIdentityExpansionCohort24V1(); const b = leaked.find((e) => e.wave === "B")!; b.profile = null; assert(validateZodianCanonicalIdentityExpansionCohort24V1(leaked).some((f) => f.code === "missing_profile"));
  const approved = listZodianCanonicalIdentityExpansionCohort24V1(); approved[0]!.approvalEvidence = ""; assert(validateZodianCanonicalIdentityExpansionCohort24V1(approved).some((f) => f.code === "approved_without_evidence"));
});

Deno.test("final Wave B lifecycle evidence and guarded transitions are explicit", () => { const waveB = getZodianCanonicalIdentityExpansionCohort24V1("Libra", "Ox")!; assertEquals(validateZodianExpansionCohortIdentityCandidateV1(waveB), []); const source = getZodianCanonicalIdentityExpansionCohort24V1("Aries", "Tiger")!.profile!; const profile = { ...source, identity: { westernSign: "Libra", chineseSign: "Ox" } }; const sourceReady = { ...waveB, status: "source_ready" as const, profile: null, approvalEvidence: undefined, reviewEvidence: undefined }; const proposed = { ...waveB, status: "editorial_review" as const, profile, approvalEvidence: undefined, reviewEvidence: { sourceSupportReviewed: true } }; assertEquals(validateZodianExpansionCohortIdentityCandidateV1(proposed), []); assert(canTransitionZodianExpansionCohortIdentityV1(sourceReady, "editorial_review", profile, proposed.reviewEvidence)); assert(!canTransitionZodianExpansionCohortIdentityV1(sourceReady, "approved", profile, waveB.reviewEvidence)); assert(!canTransitionZodianExpansionCohortIdentityV1(waveB, "editorial_review", profile, proposed.reviewEvidence)); assert(validateZodianCanonicalIdentityExpansionCohort24V1([{ ...proposed, profile: null }, ...listZodianCanonicalIdentityExpansionCohort24V1().slice(1)]).some((f) => f.code === "missing_profile")); const sheep = { ...waveB, identity: { westernSign: "Libra", chineseSign: "Sheep" } }; assert(validateZodianExpansionCohortIdentityCandidateV1(sheep).some((f) => f.code === "noncanonical_sign")); });

Deno.test("module is shadow-only and revision scope is limited", async () => {
  const source = await Deno.readTextFile(new URL("./zodian-canonical-identity-expansion-cohort-24-v1.ts", import.meta.url));
  assert(!/\b(?:fetch|supabase|rpc|database|publish|resolver|scheduler|cron|openai|provider|generate|natural-reader-writer)\b/i.test(source));
  const diff = (await new Deno.Command("git", { args: ["diff", "--name-only", "2bc92d6024b2cdc504962e51d989b2d44bac7898", "HEAD"] }).output()).stdout; const files = new TextDecoder().decode(diff).trim().split("\n").filter(Boolean); const allowed = new Set(["docs/editorial/ZODIAN_CANONICAL_IDENTITY_EXPANSION_COHORT_24_V1.md", "docs/editorial/ZODIAN_CANONICAL_IDENTITY_EXPANSION_COHORT_24_V1_REVIEW.md", "docs/editorial/ZODIAN_CANONICAL_IDENTITY_EXPANSION_COHORT_24_V1_BLIND_REVIEW.md", "supabase/functions/_shared/zodian-canonical-identity-expansion-cohort-24-v1.ts", "supabase/functions/_shared/zodian-canonical-identity-expansion-cohort-24-v1_test.ts"]); assert(files.every((file) => allowed.has(file)));
});
