import { assert, assertEquals } from "jsr:@std/assert";
import { getZodianCanonicalIdentityCohort12V2, listBlockedZodianCanonicalIdentityCohort12V2, listZodianCanonicalIdentityCohort12V2, validateZodianCanonicalIdentityCohort12V2, ZODIAN_CANONICAL_IDENTITY_COHORT_12_V2_BLIND_ENTRIES } from "./zodian-canonical-identity-cohort-12-v2.ts";
import { validateZodianIdentityEditorialProfile } from "./zodian-identity-editorial-layer-v1.ts";
import { ZODIAN_CANONICAL_IDENTITY_COHORT_12_V1_FINGERPRINT } from "./zodian-canonical-identity-cohort-12-v1-freeze.ts";
import { ZODIAN_SHADOW_NATURAL_READER_WRITER_V1_FINGERPRINT } from "./zodian-shadow-natural-reader-writer-v1-freeze.ts";

const fields=["coreMotivations","recurringStrengths","recurringFriction","commonBlindSpots","interpersonalPatterns","emotionalPatterns"] as const;
Deno.test("twelve v2 approved profiles are valid, uneven, and distinct from v1",()=>{const entries=listZodianCanonicalIdentityCohort12V2();assertEquals(entries.length,12);assertEquals(new Set(entries.map(e=>`${e.identity.westernSign}\0${e.identity.chineseSign}`)).size,12);for(const e of entries){assert(e.profile);assertEquals(validateZodianIdentityEditorialProfile(e.profile!),[]);assertEquals(e.profile!.identity,e.identity);for(const f of fields)assert(e.profile![f].length>=1&&e.profile![f].length<=4);assertEquals(e.status,"approved");assert(e.approvalEvidence);assertEquals(e.profile!.provenance!.sourceIds.length,1)}assert(entries.some(e=>e.profile!.emotionalPatterns.length===1));assertEquals(validateZodianCanonicalIdentityCohort12V2(),[]);});
Deno.test("audit catches duplicate, generic, blocked, and profile mismatches",()=>{const entries=listZodianCanonicalIdentityCohort12V2();const bad=structuredClone(entries);bad[0].profile!.coreMotivations[0]=bad[0].profile!.recurringStrengths[0];bad[1].profile!.coreMotivations[0]="Values honesty.";bad[2].profile!.identity.westernSign="Other";bad[3].status="blocked";const codes=validateZodianCanonicalIdentityCohort12V2(bad).map(x=>x.code);assert(codes.includes("same_profile_duplicate")&&codes.includes("generic_tripwire")&&codes.includes("identity_mismatch")&&codes.includes("blocked_profile"));});
Deno.test("amended notes, lookup, blind entries, review, and frozen boundaries are explicit",async()=>{const entries=listZodianCanonicalIdentityCohort12V2();const notes=entries.flatMap(e=>fields.flatMap(f=>e.profile![f]));for(const old of ["being overlooked","understated rather than plainly announced","cool severity","Early anxiety can give way"])assert(!notes.some(note=>note.includes(old)));assert(getZodianCanonicalIdentityCohort12V2("Gemini","Ox")!.profile!.commonBlindSpots[0].includes("demanding standards"));assert(getZodianCanonicalIdentityCohort12V2("Gemini","Ox")!.profile!.emotionalPatterns[0].includes("chilly"));assert(getZodianCanonicalIdentityCohort12V2("Aquarius","Dragon")!.profile!.emotionalPatterns[0].includes("worry and panic"));assert(getZodianCanonicalIdentityCohort12V2("Scorpio","Horse")!.profile!.emotionalPatterns[0].includes("anxious and guilt-prone"));assertEquals(getZodianCanonicalIdentityCohort12V2("Unknown","Unknown"),undefined);const copy=getZodianCanonicalIdentityCohort12V2("Libra","Tiger")!;copy.profile!.coreMotivations[0]="changed";assert(getZodianCanonicalIdentityCohort12V2("Libra","Tiger")!.profile!.coreMotivations[0]!=="changed");assertEquals(listBlockedZodianCanonicalIdentityCohort12V2(),[]);assertEquals(ZODIAN_CANONICAL_IDENTITY_COHORT_12_V2_BLIND_ENTRIES.length,12);const review=await Deno.readTextFile(new URL("../../../docs/editorial/ZODIAN_CANONICAL_IDENTITY_COHORT_12_V2_REVIEW.md",import.meta.url));for(const e of entries)assert(review.includes(`${e.identity.westernSign} × ${e.identity.chineseSign}`));assertEquals(ZODIAN_CANONICAL_IDENTITY_COHORT_12_V1_FINGERPRINT,"85cc707e80e9911edfeef448d01e7a8da2a0c3cb48bedf3a45958e0c17dcfb0f");assertEquals(ZODIAN_SHADOW_NATURAL_READER_WRITER_V1_FINGERPRINT,"77e1b08cc156abbfe2e16753fddd35e1e10422fbb0e391fc21ea3133500b5c20");const source=await Deno.readTextFile(new URL("./zodian-canonical-identity-cohort-12-v2.ts",import.meta.url));assert(!/\b(?:fetch|supabase|rpc|database|publish|resolver|scheduler|cron|openai|provider|generate)\b/i.test(source));});
