import { sourceMayInformDistilledEditorialProfiles } from "./zodian-canonical-source-registry-v1.ts";
import { validateZodianIdentityEditorialProfile, type ZodianIdentityEditorialProfile } from "./zodian-identity-editorial-layer-v1.ts";
import { listZodianCanonicalIdentityCohort12V1 } from "./zodian-canonical-identity-cohort-12-v1.ts";
import { listZodianCanonicalIdentityCohort12V2 } from "./zodian-canonical-identity-cohort-12-v2.ts";

export const ZODIAN_CANONICAL_IDENTITY_EXPANSION_COHORT_24_V1 = "zodian-canonical-identity-expansion-cohort-24-v1" as const;
export const ZODIAN_CANONICAL_IDENTITY_EXPANSION_SOURCE_ID = "source:suzanne-white:new-astrology-21st-century" as const;
export const ZODIAN_CANONICAL_IDENTITY_EXPANSION_SOURCE_PATH = "project_sources/01-The-New-Astrology-for-the-21st-Century-Suzanne-White-.txt" as const;
type Wave = "A" | "B";
type Status = "source_ready" | "editorial_review" | "approved" | "blocked";
export type ZodianExpansionCohort24Entry = { identity: { westernSign: string; chineseSign: string }; wave: Wave; status: Status; sourceId: typeof ZODIAN_CANONICAL_IDENTITY_EXPANSION_SOURCE_ID; sourcePath: typeof ZODIAN_CANONICAL_IDENTITY_EXPANSION_SOURCE_PATH; sourceSectionLocated: true; readyForManualDistillation: true; structuralRisk: string; nearestV1: string; nearestV2: string; profile: ZodianIdentityEditorialProfile | null };
export type ZodianExpansionCohort24Finding = { field: string; code: string; message: string };
const profile = (westernSign: string, chineseSign: string, coreMotivations: string[], recurringStrengths: string[], recurringFriction: string[], commonBlindSpots: string[], interpersonalPatterns: string[], emotionalPatterns: string[]): ZodianIdentityEditorialProfile => ({ version: "zodian-identity-editorial-layer-v1", identity: { westernSign, chineseSign }, coreMotivations, recurringStrengths, recurringFriction, commonBlindSpots, interpersonalPatterns, emotionalPatterns, provenance: { sourceIds: [ZODIAN_CANONICAL_IDENTITY_EXPANSION_SOURCE_ID] } });
const A = (westernSign: string, chineseSign: string, structuralRisk: string, nearestV1: string, nearestV2: string, p: ZodianIdentityEditorialProfile): ZodianExpansionCohort24Entry => ({ identity: { westernSign, chineseSign }, wave: "A", status: "editorial_review", sourceId: ZODIAN_CANONICAL_IDENTITY_EXPANSION_SOURCE_ID, sourcePath: ZODIAN_CANONICAL_IDENTITY_EXPANSION_SOURCE_PATH, sourceSectionLocated: true, readyForManualDistillation: true, structuralRisk, nearestV1, nearestV2, profile: p });
const B = (westernSign: string, chineseSign: string, structuralRisk: string, nearestV1: string, nearestV2: string): ZodianExpansionCohort24Entry => ({ identity: { westernSign, chineseSign }, wave: "B", status: "source_ready", sourceId: ZODIAN_CANONICAL_IDENTITY_EXPANSION_SOURCE_ID, sourcePath: ZODIAN_CANONICAL_IDENTITY_EXPANSION_SOURCE_PATH, sourceSectionLocated: true, readyForManualDistillation: true, structuralRisk, nearestV1, nearestV2, profile: null });
const ENTRIES: readonly ZodianExpansionCohort24Entry[] = Object.freeze([
  A("Aries", "Tiger", "force and escape risk", "Aries × Rat", "Aries × Ox", profile("Aries", "Tiger", ["Seeks freedom, momentum, and a cause worth pursuing."], ["Acts directly and brings sustained energy to demanding work."], ["Commitment clashes with an intense need for novelty and movement."], ["May treat constraint as a reason to leave before responsibility is settled."], ["Shares convictions openly but resists being managed by others."], ["Boredom quickly turns into impatience and restless withdrawal."])),
  A("Aries", "Dragon", "dominance boundary", "Scorpio × Dragon", "Aries × Ox", profile("Aries", "Dragon", ["Wants visible progress and room to act on large ambitions."], ["Combines nerve with persuasive personal presence."], ["Direct drive is complicated by a taste for maneuvering and display."], ["May mistake charm or confidence for permission to overreach."], ["Can draw people in, then test how much influence that attention gives."], ["Sentiment can interrupt a forceful exterior and alter a hard decision."])),
  A("Taurus", "Rat", "security and strategy", "Pisces × Ox", "Taurus × Pig", profile("Taurus", "Rat", ["Protects position, comfort, and durable material security."], ["Uses memory, patience, and precise timing to pursue an advantage."], ["Calm self-control sits beside alert calculation and appetite for influence."], ["May hide rivalry or resentment behind composure and good manners."], ["Offers protection selectively and expects loyalty in return."], ["Keeps strong feeling private, especially when dignity is at stake."])),
  A("Taurus", "Monkey", "warmth versus opportunism", "Capricorn × Monkey", "Taurus × Pig", profile("Taurus", "Monkey", ["Wants a secure life that still leaves room for pleasure and independence."], ["Combines practical follow-through with quick improvisation."], ["Steady attachments conflict with a tendency to put personal comfort first."], ["May assume self-sufficiency excuses indifference to another person's needs."], ["Is helpful and sociable without wanting constant company or dependence."], ["Recovers composure after setbacks while keeping deeper attachments intact."])),
  A("Gemini", "Rat", "verbal force and restlessness", "Gemini × Dragon", "Gemini × Ox", profile("Gemini", "Rat", ["Seeks stimulation, social access, and influence through ideas."], ["Thinks quickly, speaks easily, and notices useful openings."], ["Mental speed competes with consistency and sustained attention."], ["May treat a clever reading of people as deeper understanding than it is."], ["Builds connection through talk, charm, and strategic sociability."], ["Nervous energy can turn a small uncertainty into restless activity."])),
  A("Gemini", "Sheep", "sensitivity grounding", "Sagittarius × Sheep", "Gemini × Ox", profile("Gemini", "Sheep", ["Wants expressive freedom alongside acceptance and reassurance."], ["Brings verbal versatility to imaginative interests."], ["Curiosity and performance instincts compete with hesitation about exposure."], ["May delay a choice while searching for a safer or more pleasing version."], ["Uses conversation to seek closeness but can retreat when reception feels uncertain."], ["Sensitivity to criticism can make confidence uneven and changeable."])),
  A("Cancer", "Tiger", "care versus intensity", "Cancer × Pig", "Cancer × Rat", profile("Cancer", "Tiger", ["Protects loved ones, personal freedom, and strongly held loyalties."], ["Combines courage with tenacious care for a chosen circle."], ["Private sensitivity conflicts with a forceful refusal to be constrained."], ["May turn hurt or protectiveness into possessiveness or defiance."], ["Can be warm and magnetic while resisting demands that feel controlling."], ["Mood shifts sharpen when affection, pride, or freedom feels threatened."])),
  A("Cancer", "Dragon", "control and exposure", "Scorpio × Dragon", "Cancer × Rat", profile("Cancer", "Dragon", ["Wants emotional security, recognition, and authority over the home base."], ["Pairs imagination and persistence with bold personal force."], ["Need for closeness competes with pride and a wish to direct outcomes."], ["May make emotional certainty sound like the only acceptable version of events."], ["Protects intensely and can become commanding when attachment is involved."], ["Sensitivity and irritation can rise quickly beneath a composed front."])),
  A("Leo", "Rat", "attention and guardedness", "Gemini × Dragon", "Leo × Dog", profile("Leo", "Rat", ["Seeks admiration, influence, and a lively social position."], ["Combines warmth and theatrical confidence with alert social intelligence."], ["A need to shine competes with watchfulness about status and advantage."], ["May read low attention as a slight and respond with display or control."], ["Draws others in easily but keeps track of loyalty and standing."], ["Anxiety can sit behind a polished, expansive social manner."])),
  A("Leo", "Pig", "comfort and pride", "Cancer × Pig", "Leo × Horse", profile("Leo", "Pig", ["Wants affection, comfort, and a life that reflects high personal standards."], ["Offers warmth, generosity, and a strong sense of style."], ["Loyal feeling competes with indulgence, vanity, and reluctance to accept less."], ["May withdraw effort when admiration or quality falls short of expectation."], ["Treats close bonds seriously yet expects devotion and discretion in return."], ["Disappointment is often redirected into humor, pride, or private discouragement."])),
  A("Virgo", "Horse", "precision and freedom", "Scorpio × Horse", "Virgo × Cat", profile("Virgo", "Horse", ["Wants excellence, recognition, and freedom to pursue visible aims."], ["Applies discernment and polish to ambitious, public-facing efforts."], ["Exacting standards conflict with impatience for limits or slower processes."], ["May justify self-serving shortcuts as necessary progress."], ["Is charming and demanding, expecting others to meet a high bar."], ["Confidence can harden into vanity or anxiety about falling short."])),
  A("Virgo", "Monkey", "analysis and opportunism", "Capricorn × Monkey", "Virgo × Dragon", profile("Virgo", "Monkey", ["Wants control, security, and recognition for discerning judgment."], ["Combines close analysis with wit, practical skill, and improvisation."], ["Careful standards conflict with opportunism and a wish to direct other people."], ["May turn accurate criticism into meddling or use generosity to secure approval."], ["Offers assistance readily but can expect deference and gratitude in return."], ["Insecurity can become nervous control, self-pity, or blame after disappointment."])),
  B("Libra", "Ox", "warmth and restraint", "Virgo × Cat", "Libra × Tiger"), B("Libra", "Dragon", "charm and dominance", "Scorpio × Dragon", "Libra × Tiger"), B("Scorpio", "Rat", "strategy and social force", "Cancer × Rat", "Scorpio × Horse"), B("Scorpio", "Pig", "intensity and comfort", "Cancer × Pig", "Scorpio × Horse"), B("Sagittarius", "Ox", "freedom and stability", "Gemini × Ox", "Sagittarius × Sheep"), B("Sagittarius", "Dragon", "ambition and excess", "Scorpio × Dragon", "Sagittarius × Monkey"), B("Capricorn", "Tiger", "discipline and rebellion", "Aries × Ox", "Capricorn × Monkey"), B("Capricorn", "Horse", "duty and mobility", "Leo × Horse", "Capricorn × Rooster"), B("Aquarius", "Rat", "social intelligence and distance", "Cancer × Rat", "Aquarius × Snake"), B("Aquarius", "Pig", "care and indulgence", "Cancer × Pig", "Aquarius × Dragon"), B("Pisces", "Tiger", "sensitivity and force", "Scorpio × Horse", "Pisces × Ox"), B("Pisces", "Dragon", "imagination and dominance", "Scorpio × Dragon", "Pisces × Ox"),
]);
const FIELDS = ["coreMotivations", "recurringStrengths", "recurringFriction", "commonBlindSpots", "interpersonalPatterns", "emotionalPatterns"] as const;
const key = (identity: { westernSign: string; chineseSign: string }) => `${identity.westernSign}\0${identity.chineseSign}`;
const normal = (note: string) => note.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
const GENERIC = /\b(?:natural leader|values honesty|cares deeply|works hard|seeks success|needs balance|highly intuitive|deeply loyal|emotionally available|strong communicator|adaptable|resilient|strategic thinker|dependable|trustworthy)\b/i;
const cloneProfile = (p: ZodianIdentityEditorialProfile | null) => p && { ...p, identity: { ...p.identity }, coreMotivations: [...p.coreMotivations], recurringStrengths: [...p.recurringStrengths], recurringFriction: [...p.recurringFriction], commonBlindSpots: [...p.commonBlindSpots], interpersonalPatterns: [...p.interpersonalPatterns], emotionalPatterns: [...p.emotionalPatterns], provenance: p.provenance && { sourceIds: [...p.provenance.sourceIds] } };
const clone = (e: ZodianExpansionCohort24Entry): ZodianExpansionCohort24Entry => ({ ...e, identity: { ...e.identity }, profile: cloneProfile(e.profile) });
export const listZodianCanonicalIdentityExpansionCohort24V1 = () => ENTRIES.map(clone);
export const listZodianCanonicalIdentityExpansionWave = (wave: Wave) => ENTRIES.filter((e) => e.wave === wave).map(clone);
export const getZodianCanonicalIdentityExpansionCohort24V1 = (westernSign: string, chineseSign: string) => { const entry = ENTRIES.find((e) => e.identity.westernSign === westernSign && e.identity.chineseSign === chineseSign); return entry && clone(entry); };
export function validateZodianCanonicalIdentityExpansionCohort24V1(entries: readonly ZodianExpansionCohort24Entry[] = ENTRIES): ZodianExpansionCohort24Finding[] {
  const findings: ZodianExpansionCohort24Finding[] = []; const add = (field: string, code: string, message: string) => findings.push({ field, code, message }); const seen = new Set<string>(); const notes = new Map<string, string>(); const v1 = new Set(listZodianCanonicalIdentityCohort12V1().map((e) => key(e.identity))); const v2 = new Set(listZodianCanonicalIdentityCohort12V2().map((e) => key(e.identity)));
  if (entries.length !== 24) add("cohort", "incorrect_size", "Expansion cohort must contain 24 identities."); const a = entries.filter((e) => e.wave === "A"), b = entries.filter((e) => e.wave === "B"); if (a.length !== 12) add("wave.A", "incorrect_size", "Wave A must contain 12 identities."); if (b.length !== 12) add("wave.B", "incorrect_size", "Wave B must contain 12 identities.");
  for (const entry of entries) { const identityKey = key(entry.identity); if (seen.has(identityKey)) add("identity", "duplicate_identity", "Duplicate identity."); seen.add(identityKey); if (v1.has(identityKey)) add("identity", "reused_v1_identity", "Expansion cannot reuse v1 identity."); if (v2.has(identityKey)) add("identity", "reused_v2_identity", "Expansion cannot reuse v2 identity."); if (!sourceMayInformDistilledEditorialProfiles(entry.sourceId) || entry.sourcePath !== ZODIAN_CANONICAL_IDENTITY_EXPANSION_SOURCE_PATH || !entry.sourceSectionLocated || !entry.readyForManualDistillation) add("source", "invalid_source", "Approved source readiness is required."); if (entry.wave === "B" && (entry.status !== "source_ready" || entry.profile !== null)) add("wave.B", "wave_b_leakage", "Wave B must remain source_ready and profile-free."); if (entry.wave === "A" && entry.status === "approved") add("wave.A", "premature_approval", "Wave A is not approved in this milestone."); if (entry.status === "blocked" && entry.profile) add("profile", "blocked_profile", "Blocked identity cannot expose a profile."); if (entry.wave === "A" && entry.status === "editorial_review" && !entry.profile) add("profile", "missing_profile", "Completed Wave A entry needs a profile."); if (!entry.profile) continue; if (entry.profile.identity.westernSign !== entry.identity.westernSign || entry.profile.identity.chineseSign !== entry.identity.chineseSign) add("profile.identity", "identity_mismatch", "Profile identity differs."); for (const finding of validateZodianIdentityEditorialProfile(entry.profile)) add(finding.field, "invalid_profile", finding.message); const local = new Set<string>(); for (const field of FIELDS) { const values = entry.profile[field]; if (values.length < 1 || values.length > 4) add(field, "note_count", "Category needs one to four notes."); const category = values.map(normal).join("|"); if (new Set(values.map(normal)).size !== values.length) add(field, "duplicate_category", "Category contains duplicate notes."); for (const note of values) { const normalized = normal(note); if (!normalized || /\b(?:todo|tbd|placeholder)\b/i.test(note)) add(field, "placeholder", "Placeholder notes are not allowed."); if (GENERIC.test(note)) add(field, "generic_tripwire", "Generic wording needs human review."); if (local.has(normalized)) add(field, "same_profile_duplicate", "Duplicate across profile fields."); local.add(normalized); if (notes.has(normalized)) add(field, "normalized_duplicate", `Duplicates ${notes.get(normalized)}.`); else notes.set(normalized, `${identityKey}.${field}`); } void category; } }
  return findings;
}
export const ZODIAN_CANONICAL_IDENTITY_EXPANSION_COHORT_24_V1_BLIND_ENTRIES = Object.freeze(["expansion-24-08", "expansion-24-03", "expansion-24-11", "expansion-24-01", "expansion-24-06", "expansion-24-09", "expansion-24-04", "expansion-24-12", "expansion-24-02", "expansion-24-10", "expansion-24-05", "expansion-24-07"]);
export type ZodianExpansionCohort24BlindEntry = { anonymousId: string } & Pick<ZodianIdentityEditorialProfile, typeof FIELDS[number]>;
export const listZodianCanonicalIdentityExpansionCohort24V1BlindEntries = (): ZodianExpansionCohort24BlindEntry[] => ZODIAN_CANONICAL_IDENTITY_EXPANSION_COHORT_24_V1_BLIND_ENTRIES.map((anonymousId) => { const index = Number(anonymousId.slice(-2)) - 1; const p = ENTRIES.filter((entry) => entry.wave === "A")[index]!.profile!; return { anonymousId, ...Object.fromEntries(FIELDS.map((field) => [field, [...p[field]]])) } as ZodianExpansionCohort24BlindEntry; });
