import { sourceMayInformDistilledEditorialProfiles } from "./zodian-canonical-source-registry-v1.ts";
export const ZODIAN_CANONICAL_IDENTITY_EXPANSION_COHORT_24_V1="zodian-canonical-identity-expansion-cohort-24-v1" as const;
const S="source:suzanne-white:new-astrology-21st-century" as const, P="project_sources/01-The-New-Astrology-for-the-21st-Century-Suzanne-White-.txt";
export type Entry={identity:{westernSign:string;chineseSign:string};wave:"A"|"B";status:"source_ready";sourceId:typeof S;sourcePath:string;sourceSectionLocated:true;readyForManualDistillation:true;structuralRisk:string;nearestV1:string;nearestV2:string;profile:null};
const rows=[
["Aries","Tiger","A","force and escape risk","Aries × Rat","Aries × Ox"],["Aries","Dragon","A","dominance boundary","Scorpio × Dragon","Aries × Ox"],["Taurus","Rat","A","security and strategy","Pisces × Ox","Taurus × Pig"],["Taurus","Monkey","A","warmth versus opportunism","Capricorn × Monkey","Taurus × Pig"],["Gemini","Rat","A","verbal force and restlessness","Gemini × Dragon","Gemini × Ox"],["Gemini","Sheep","A","sensitivity grounding","Sagittarius × Sheep","Gemini × Ox"],["Cancer","Tiger","A","care versus intensity","Cancer × Pig","Cancer × Rat"],["Cancer","Dragon","A","control and exposure","Scorpio × Dragon","Cancer × Rat"],["Leo","Rat","A","attention and guardedness","Gemini × Dragon","Leo × Dog"],["Leo","Pig","A","comfort and pride","Cancer × Pig","Leo × Horse"],["Virgo","Horse","A","precision and freedom","Scorpio × Horse","Virgo × Cat"],["Virgo","Monkey","A","analysis and opportunism","Capricorn × Monkey","Virgo × Dragon"],["Libra","Ox","B","warmth and restraint","Virgo × Cat","Libra × Tiger"],["Libra","Dragon","B","charm and dominance","Scorpio × Dragon","Libra × Tiger"],["Scorpio","Rat","B","strategy and social force","Cancer × Rat","Scorpio × Horse"],["Scorpio","Pig","B","intensity and comfort","Cancer × Pig","Scorpio × Horse"],["Sagittarius","Ox","B","freedom and stability","Gemini × Ox","Sagittarius × Sheep"],["Sagittarius","Dragon","B","ambition and excess","Scorpio × Dragon","Sagittarius × Monkey"],["Capricorn","Tiger","B","discipline and rebellion","Aries × Ox","Capricorn × Monkey"],["Capricorn","Horse","B","duty and mobility","Leo × Horse","Capricorn × Rooster"],["Aquarius","Rat","B","social intelligence and distance","Cancer × Rat","Aquarius × Snake"],["Aquarius","Pig","B","care and indulgence","Cancer × Pig","Aquarius × Dragon"],["Pisces","Tiger","B","sensitivity and force","Scorpio × Horse","Pisces × Ox"],["Pisces","Dragon","B","imagination and dominance","Scorpio × Dragon","Pisces × Ox"]] as const;
const E:readonly Entry[]=Object.freeze(rows.map(([westernSign,chineseSign,wave,structuralRisk,nearestV1,nearestV2])=>Object.freeze({identity:Object.freeze({westernSign,chineseSign}),wave,status:"source_ready" as const,sourceId:S,sourcePath:P,sourceSectionLocated:true as const,readyForManualDistillation:true as const,structuralRisk,nearestV1,nearestV2,profile:null})));
const clone=(e:Entry):Entry=>({...e,identity:{...e.identity}});export const listZodianCanonicalIdentityExpansionCohort24V1=()=>E.map(clone);export const listZodianCanonicalIdentityExpansionWave=(wave:"A"|"B")=>E.filter(e=>e.wave===wave).map(clone);export const getZodianCanonicalIdentityExpansionCohort24V1=(w:string,c:string)=>{const e=E.find(x=>x.identity.westernSign===w&&x.identity.chineseSign===c);return e&&clone(e)};export const validateZodianCanonicalIdentityExpansionCohort24V1=()=>E.length===24&&new Set(E.map(e=>`${e.identity.westernSign}\0${e.identity.chineseSign}`)).size===24&&E.every(e=>e.profile===null&&sourceMayInformDistilledEditorialProfiles(e.sourceId))?[]:["invalid expansion scaffold"];
export const ZODIAN_CANONICAL_IDENTITY_EXPANSION_COHORT_24_V1_BLIND_IDS=Object.freeze(Array.from({length:24},(_,i)=>`expansion-24-${String(i+1).padStart(2,"0")}`));
