import { sourceMayInformDistilledEditorialProfiles } from "./zodian-canonical-source-registry-v1.ts";
import { validateZodianIdentityEditorialProfile, type ZodianIdentityEditorialProfile } from "./zodian-identity-editorial-layer-v1.ts";
import { listZodianCanonicalIdentityCohort12V1 } from "./zodian-canonical-identity-cohort-12-v1.ts";
import { listZodianCanonicalIdentityCohort12V2 } from "./zodian-canonical-identity-cohort-12-v2.ts";
import { canTransitionZodianExpansionProfileStatusV1, validateZodianExpansionProfileLifecycleStateV1, type ZodianExpansionProfileReviewEvidenceV1, type ZodianExpansionProfileStatusV1 } from "./zodian-expansion-profile-lifecycle-v1.ts";

export const ZODIAN_CANONICAL_IDENTITY_EXPANSION_COHORT_24_V1 = "zodian-canonical-identity-expansion-cohort-24-v1" as const;
export const ZODIAN_CANONICAL_IDENTITY_EXPANSION_SOURCE_ID = "source:suzanne-white:new-astrology-21st-century" as const;
export const ZODIAN_CANONICAL_IDENTITY_EXPANSION_SOURCE_PATH = "project_sources/01-The-New-Astrology-for-the-21st-Century-Suzanne-White-.txt" as const;
type Wave = "A" | "B";
type Status = "source_ready" | "editorial_review" | "approved" | "blocked";
export type ZodianExpansionCohort24Entry = { identity: { westernSign: string; chineseSign: string }; wave: Wave; status: Status; approvalEvidence?: string; reviewEvidence?: ZodianExpansionProfileReviewEvidenceV1; sourceId: typeof ZODIAN_CANONICAL_IDENTITY_EXPANSION_SOURCE_ID; sourcePath: typeof ZODIAN_CANONICAL_IDENTITY_EXPANSION_SOURCE_PATH; sourceSectionLocated: true; readyForManualDistillation: true; structuralRisk: string; nearestV1: string; nearestV2: string; profile: ZodianIdentityEditorialProfile | null };
export type ZodianExpansionCohort24Finding = { field: string; code: string; message: string };
const profile = (westernSign: string, chineseSign: string, coreMotivations: string[], recurringStrengths: string[], recurringFriction: string[], commonBlindSpots: string[], interpersonalPatterns: string[], emotionalPatterns: string[]): ZodianIdentityEditorialProfile => ({ version: "zodian-identity-editorial-layer-v1", identity: { westernSign, chineseSign }, coreMotivations, recurringStrengths, recurringFriction, commonBlindSpots, interpersonalPatterns, emotionalPatterns, provenance: { sourceIds: [ZODIAN_CANONICAL_IDENTITY_EXPANSION_SOURCE_ID] } });
const A = (westernSign: string, chineseSign: string, structuralRisk: string, nearestV1: string, nearestV2: string, p: ZodianIdentityEditorialProfile): ZodianExpansionCohort24Entry => ({ identity: { westernSign, chineseSign }, wave: "A", status: "approved", approvalEvidence: "wave-a-final-source-support-blind-and-usefulness-review", sourceId: ZODIAN_CANONICAL_IDENTITY_EXPANSION_SOURCE_ID, sourcePath: ZODIAN_CANONICAL_IDENTITY_EXPANSION_SOURCE_PATH, sourceSectionLocated: true, readyForManualDistillation: true, structuralRisk, nearestV1, nearestV2, profile: p });
const B = (westernSign: string, chineseSign: string, structuralRisk: string, nearestV1: string, nearestV2: string): ZodianExpansionCohort24Entry => ({ identity: { westernSign, chineseSign }, wave: "B", status: "source_ready", sourceId: ZODIAN_CANONICAL_IDENTITY_EXPANSION_SOURCE_ID, sourcePath: ZODIAN_CANONICAL_IDENTITY_EXPANSION_SOURCE_PATH, sourceSectionLocated: true, readyForManualDistillation: true, structuralRisk, nearestV1, nearestV2, profile: null });
const R = (westernSign: string, chineseSign: string, structuralRisk: string, nearestV1: string, nearestV2: string, p: ZodianIdentityEditorialProfile): ZodianExpansionCohort24Entry => ({ identity: { westernSign, chineseSign }, wave: "B", status: "editorial_review", reviewEvidence: { sourceSupportReviewed: true }, sourceId: ZODIAN_CANONICAL_IDENTITY_EXPANSION_SOURCE_ID, sourcePath: ZODIAN_CANONICAL_IDENTITY_EXPANSION_SOURCE_PATH, sourceSectionLocated: true, readyForManualDistillation: true, structuralRisk, nearestV1, nearestV2, profile: p });
const ENTRIES: readonly ZodianExpansionCohort24Entry[] = Object.freeze([
  A("Aries", "Tiger", "force and escape risk", "Aries × Rat", "Aries × Ox", profile("Aries", "Tiger", ["Seeks room to act independently.", "Needs movement and change rather than prolonged constraint."], ["Meets resistance with direct force."], ["Commitment can collide with impatience when freedom feels limited.", "Personal certainty can harden against shared rules."], ["May leave a demanding situation rather than remain constrained."], ["States convictions plainly and resists being directed by others."], ["Boredom can become hot impatience and abrupt withdrawal."])),
  A("Aries", "Dragon", "dominance boundary", "Scorpio × Dragon", "Aries × Ox", profile("Aries", "Dragon", ["Wants visible advancement and room for large ambitions."], ["Acts with nerve and bold presentation."], ["Direct drive sits beside maneuvering and a wish to display success.", "Pride can make restraint difficult."], ["May underestimate how conspicuous self-display or cleverness appears to others."], ["Draws attention easily and can turn interaction into a contest of presence."], ["Sentiment can interrupt forceful momentum and complicate a hard choice."])),
  A("Taurus", "Rat", "security and strategy", "Pisces × Ox", "Taurus × Pig", profile("Taurus", "Rat", ["Protects position, comfort, and durable material security."], ["Uses memory, patience, and precise timing."], ["Composure sits beside alert calculation and an appetite for influence."], ["May keep calculation private behind polished manners."], ["Protects selected people while remaining guarded about access and possession."], ["Keeps strong feeling private when dignity is at stake."])),
  A("Taurus", "Monkey", "warmth versus opportunism", "Capricorn × Monkey", "Taurus × Pig", profile("Taurus", "Monkey", ["Wants material comfort and freedom to follow personal rhythms."], ["Combines practical follow-through with quick improvisation."], ["Stable attachments compete with a strong preference for independence.", "Comfort can compete with willingness to disrupt a settled rhythm."], ["May treat a private preference as sufficient reason to step away."], ["Is helpful and sociable without needing constant company."], ["Keeps composure through setbacks but does not readily abandon chosen attachments."])),
  A("Gemini", "Rat", "verbal force and restlessness", "Gemini × Dragon", "Gemini × Ox", profile("Gemini", "Rat", ["Seeks stimulation, talk, and access to lively social settings."], ["Thinks quickly and spots openings in conversation."], ["Mental speed competes with consistency and sustained attention.", "Curiosity can scatter effort across too many directions."], ["May mistake a quick interpretation for a complete understanding."], ["Builds contact through talk, charm, and shifting social attention."], ["Nervous energy can turn uncertainty into restless movement.", "Interest can fade once novelty is gone."])),
  A("Gemini", "Goat", "sensitivity grounding", "Sagittarius × Goat", "Gemini × Ox", profile("Gemini", "Goat", ["Wants room for imaginative expression."], ["Brings verbal versatility to inventive interests."], ["Curiosity competes with hesitation and lack of foresight."], ["May delay decisions while keeping several pleasing possibilities open."], ["Seeks company while remaining guarded about personal information."], ["Worry and pessimism can sit beside quick shifts in interest."])),
  A("Cancer", "Tiger", "care versus intensity", "Cancer × Pig", "Cancer × Rat", profile("Cancer", "Tiger", ["Protects close attachments and personal freedom."], ["Combines tenacious care with forceful courage."], ["Private sensitivity conflicts with a hard refusal to be constrained.", "Protectiveness can become possessive or defiant."], ["May miss how quickly care has turned into resistance to influence."], ["Is warm and magnetic but pushes back against controlling demands."], ["Threatened affection or freedom can bring irritation and a forceful response."])),
  A("Cancer", "Dragon", "control and exposure", "Scorpio × Dragon", "Cancer × Rat", profile("Cancer", "Dragon", ["Wants emotional security, recognition, and a strong say in close life."], ["Pairs imagination and persistence with bold personal force."], ["Need for closeness competes with pride and a wish to direct outcomes."], ["May overlook how commanding certainty feels to another person."], ["Protects intensely and can become controlling when attachment is involved."], ["Sensitivity and irritation can rise quickly beneath pride and composure."])),
  A("Leo", "Rat", "attention and guardedness", "Gemini × Dragon", "Leo × Dog", profile("Leo", "Rat", ["Seeks admiration, pleasure, and a visible place among others."], ["Combines warmth and showmanship with alertness to social shifts."], ["A need to shine competes with watchfulness about status and advantage.", "Appetite for attention can conflict with guarded self-protection."], ["May treat low attention as a slight rather than incomplete information."], ["Draws people in through display while remaining watchful about standing."], ["Anxiety can sit beneath an expansive, polished manner."])),
  A("Leo", "Pig", "comfort and pride", "Cancer × Pig", "Leo × Horse", profile("Leo", "Pig", ["Wants affection, comfort, and surroundings that meet high standards."], ["Offers warmth, generosity, and cultivated taste."], ["Loyal feeling competes with indulgence, vanity, and reluctance to accept less."], ["May overlook how high standards make ordinary compromise feel beneath consideration."], ["Treats close bonds seriously while valuing discretion and comfort."], ["Disappointment can turn into humor, pride, or private discouragement."])),
  A("Virgo", "Horse", "precision and freedom", "Scorpio × Horse", "Virgo × Cat", profile("Virgo", "Horse", ["Wants excellence, recognition, and freedom of movement."], ["Applies discernment, polish, and inventive energy to chosen aims."], ["Exacting standards conflict with impatience for limits or slower processes.", "Ambition can compete with restraint and fairness."], ["May treat a useful shortcut as more important than its effect on others."], ["Is charming and demanding, expecting others to meet a high bar."], ["Confidence can harden into vanity or anxiety about falling short."])),
  A("Virgo", "Monkey", "analysis and opportunism", "Capricorn × Monkey", "Virgo × Dragon", profile("Virgo", "Monkey", ["Wants control, security, and recognition for discerning judgment."], ["Combines close analysis with wit, practical skill, and improvisation."], ["Careful standards conflict with opportunism and a wish to direct other people.", "Possessiveness can sit beneath helpful attention."], ["May fail to see when accurate criticism has become meddling."], ["Offers practical help and unsolicited direction."], ["Disappointment can become nervous control, self-pity, or blame."])),
  R("Libra", "Ox", "warmth and restraint", "Virgo × Cat", "Libra × Tiger", profile("Libra", "Ox", ["Wants order, beauty, and a secure home base."], ["Uses words gracefully and sustains demanding standards."], ["A wish for calm competes with attraction to emotional complexity."], ["May return to a disappointing pattern while expecting a different result."], ["Offers care and structure while becoming quarrelsome or manipulative in close conflict."], ["Disillusionment can stir a busy inner life beneath a controlled surface."])),
  R("Libra", "Dragon", "charm and dominance", "Scorpio × Dragon", "Libra × Tiger", profile("Libra", "Dragon", ["Wants attention, distinction, and room to shape an unusual life."], ["Combines verbal flair with persistent self-direction."], ["A wish for harmony conflicts with pride and a refusal to yield the spotlight."], ["May overlook how display and certainty crowd out another point of view."], ["Draws others in with charm but expects lasting admiration."], ["Feeling overlooked can turn warmth into sharp resentment."])),
  R("Scorpio", "Rat", "strategy and social force", "Cancer × Rat", "Scorpio × Horse", profile("Scorpio", "Rat", ["Wants a potent place and security for a chosen circle."], ["Combines charm, criticism, and quick practical judgment."], ["Creative interest competes with the need to compete and prevail."], ["May treat suspicion or hasty judgment as sufficient evidence."], ["Entertains generously while keeping a close account of advantage and loyalty."], ["Nervousness and suspicion can grow into worry after disapproval or setback."])),
  B("Scorpio", "Pig", "intensity and comfort", "Cancer × Pig", "Scorpio × Horse"), B("Sagittarius", "Ox", "freedom and stability", "Gemini × Ox", "Sagittarius × Goat"), B("Sagittarius", "Dragon", "ambition and excess", "Scorpio × Dragon", "Sagittarius × Monkey"), B("Capricorn", "Tiger", "discipline and rebellion", "Aries × Ox", "Capricorn × Monkey"), B("Capricorn", "Horse", "duty and mobility", "Leo × Horse", "Capricorn × Rooster"), B("Aquarius", "Rat", "social intelligence and distance", "Cancer × Rat", "Aquarius × Snake"), B("Aquarius", "Pig", "care and indulgence", "Cancer × Pig", "Aquarius × Dragon"), B("Pisces", "Tiger", "sensitivity and force", "Scorpio × Horse", "Pisces × Ox"), B("Pisces", "Dragon", "imagination and dominance", "Scorpio × Dragon", "Pisces × Ox"),
]);
const FIELDS = ["coreMotivations", "recurringStrengths", "recurringFriction", "commonBlindSpots", "interpersonalPatterns", "emotionalPatterns"] as const;
const key = (identity: { westernSign: string; chineseSign: string }) => `${identity.westernSign}\0${identity.chineseSign}`;
const normal = (note: string) => note.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
const GENERIC = /\b(?:natural leader|values honesty|cares deeply|works hard|seeks success|needs balance|highly intuitive|deeply loyal|emotionally available|strong communicator|adaptable|resilient|strategic thinker|dependable|trustworthy)\b/i;
const cloneProfile = (p: ZodianIdentityEditorialProfile | null) => p && { ...p, identity: { ...p.identity }, coreMotivations: [...p.coreMotivations], recurringStrengths: [...p.recurringStrengths], recurringFriction: [...p.recurringFriction], commonBlindSpots: [...p.commonBlindSpots], interpersonalPatterns: [...p.interpersonalPatterns], emotionalPatterns: [...p.emotionalPatterns], provenance: p.provenance && { sourceIds: [...p.provenance.sourceIds] } };
const clone = (e: ZodianExpansionCohort24Entry): ZodianExpansionCohort24Entry => ({ ...e, identity: { ...e.identity }, profile: cloneProfile(e.profile) });
export const listZodianCanonicalIdentityExpansionCohort24V1 = () => ENTRIES.map(clone);
export const listZodianCanonicalIdentityExpansionWave = (wave: Wave) => ENTRIES.filter((e) => e.wave === wave).map(clone);
export const getZodianCanonicalIdentityExpansionCohort24V1 = (westernSign: string, chineseSign: string) => { const entry = ENTRIES.find((e) => e.identity.westernSign === westernSign && e.identity.chineseSign === chineseSign); return entry && clone(entry); };
/** Validates a proposed record without mutating the canonical scaffold. */
export function validateZodianExpansionCohortIdentityCandidateV1(record: ZodianExpansionCohort24Entry): ZodianExpansionCohort24Finding[] {
  const findings: ZodianExpansionCohort24Finding[] = [];
  if (record.identity.chineseSign === "Sheep") findings.push({ field: "identity.chineseSign", code: "noncanonical_sign", message: "Use Goat as the canonical Zodian identity label." });
  if (record.wave === "A" && record.status !== "approved") findings.push({ field: "status", code: "wave_a_regression", message: "Wave A cannot regress from approved." });
  if (record.profile && (record.profile.identity.westernSign !== record.identity.westernSign || record.profile.identity.chineseSign !== record.identity.chineseSign)) findings.push({ field: "profile.identity", code: "identity_mismatch", message: "Profile identity differs." });
  for (const finding of validateZodianExpansionProfileLifecycleStateV1({ status: record.status as ZodianExpansionProfileStatusV1, profile: record.profile, reviewEvidence: record.reviewEvidence })) findings.push({ field: finding.field, code: finding.code, message: finding.message });
  return findings;
}
export function canTransitionZodianExpansionCohortIdentityV1(record: ZodianExpansionCohort24Entry, nextStatus: ZodianExpansionProfileStatusV1, nextProfile: ZodianIdentityEditorialProfile | null, nextReviewEvidence?: ZodianExpansionProfileReviewEvidenceV1): boolean {
  if (record.wave === "A" || nextProfile?.identity.westernSign !== undefined && (nextProfile.identity.westernSign !== record.identity.westernSign || nextProfile.identity.chineseSign !== record.identity.chineseSign)) return false;
  return canTransitionZodianExpansionProfileStatusV1(record.status, { status: nextStatus, profile: nextProfile, reviewEvidence: nextReviewEvidence });
}
function validateZodianCanonicalIdentityExpansionCohort24ScaffoldV1(entries: readonly ZodianExpansionCohort24Entry[] = ENTRIES): ZodianExpansionCohort24Finding[] {
  const findings: ZodianExpansionCohort24Finding[] = []; const add = (field: string, code: string, message: string) => findings.push({ field, code, message }); const seen = new Set<string>(); const notes = new Map<string, string>(); const v1 = new Set(listZodianCanonicalIdentityCohort12V1().map((e) => key(e.identity))); const v2 = new Set(listZodianCanonicalIdentityCohort12V2().map((e) => key(e.identity)));
  if (entries.length !== 24) add("cohort", "incorrect_size", "Expansion cohort must contain 24 identities."); const a = entries.filter((e) => e.wave === "A"), b = entries.filter((e) => e.wave === "B"); if (a.length !== 12) add("wave.A", "incorrect_size", "Wave A must contain 12 identities."); if (b.length !== 12) add("wave.B", "incorrect_size", "Wave B must contain 12 identities.");
  for (const entry of entries) { const identityKey = key(entry.identity); if (seen.has(identityKey)) add("identity", "duplicate_identity", "Duplicate identity."); seen.add(identityKey); if (v1.has(identityKey)) add("identity", "reused_v1_identity", "Expansion cannot reuse v1 identity."); if (v2.has(identityKey)) add("identity", "reused_v2_identity", "Expansion cannot reuse v2 identity."); if (!sourceMayInformDistilledEditorialProfiles(entry.sourceId) || entry.sourcePath !== ZODIAN_CANONICAL_IDENTITY_EXPANSION_SOURCE_PATH || !entry.sourceSectionLocated || !entry.readyForManualDistillation) add("source", "invalid_source", "Approved source readiness is required."); if (entry.wave === "B" && (entry.status !== "source_ready" || entry.profile !== null)) add("wave.B", "wave_b_leakage", "Wave B must remain source_ready and profile-free."); if (entry.status === "approved" && !entry.approvalEvidence?.trim()) add("status", "approved_without_evidence", "Approved entry needs final review evidence."); if (entry.status === "blocked" && entry.profile) add("profile", "blocked_profile", "Blocked identity cannot expose a profile."); if (entry.wave === "A" && entry.status === "editorial_review" && !entry.profile) add("profile", "missing_profile", "Completed Wave A entry needs a profile."); if (!entry.profile) continue; if (entry.profile.identity.westernSign !== entry.identity.westernSign || entry.profile.identity.chineseSign !== entry.identity.chineseSign) add("profile.identity", "identity_mismatch", "Profile identity differs."); for (const finding of validateZodianIdentityEditorialProfile(entry.profile)) add(finding.field, "invalid_profile", finding.message); const local = new Set<string>(); for (const field of FIELDS) { const values = entry.profile[field]; if (values.length < 1 || values.length > 4) add(field, "note_count", "Category needs one to four notes."); const category = values.map(normal).join("|"); if (new Set(values.map(normal)).size !== values.length) add(field, "duplicate_category", "Category contains duplicate notes."); for (const note of values) { const normalized = normal(note); if (!normalized || /\b(?:todo|tbd|placeholder)\b/i.test(note)) add(field, "placeholder", "Placeholder notes are not allowed."); if (GENERIC.test(note)) add(field, "generic_tripwire", "Generic wording needs human review."); if (local.has(normalized)) add(field, "same_profile_duplicate", "Duplicate across profile fields."); local.add(normalized); if (notes.has(normalized)) add(field, "normalized_duplicate", `Duplicates ${notes.get(normalized)}.`); else notes.set(normalized, `${identityKey}.${field}`); } void category; } }
  return findings;
}
/**
 * Canonical cohort validation: lifecycle owns Wave B state/profile invariants;
 * the retained scaffold validator owns only expansion structure and references.
 */
export function validateZodianCanonicalIdentityExpansionCohort24V1(entries: readonly ZodianExpansionCohort24Entry[] = ENTRIES): ZodianExpansionCohort24Finding[] {
  const scaffold = entries.map((entry) => entry.wave === "B" ? { ...entry, status: "source_ready" as const, profile: null, reviewEvidence: undefined } : entry);
  const findings = validateZodianCanonicalIdentityExpansionCohort24ScaffoldV1(scaffold);
  entries.forEach((entry, index) => { if (entry.wave !== "B") return; for (const finding of validateZodianExpansionCohortIdentityCandidateV1(entry)) findings.push({ field: `entries.${index}.${finding.field}`, code: finding.code, message: finding.message }); if (entry.profile && (entry.profile.provenance?.sourceIds.length !== 1 || entry.profile.provenance?.sourceIds[0] !== entry.sourceId)) findings.push({ field: `entries.${index}.profile.provenance.sourceIds`, code: "invalid_provenance", message: "Profile provenance must match the cohort source." }); });
  return findings;
}
export const ZODIAN_CANONICAL_IDENTITY_EXPANSION_COHORT_24_V1_BLIND_ENTRIES = Object.freeze(["expansion-24-08", "expansion-24-03", "expansion-24-11", "expansion-24-01", "expansion-24-06", "expansion-24-09", "expansion-24-04", "expansion-24-12", "expansion-24-02", "expansion-24-10", "expansion-24-05", "expansion-24-07"]);
export type ZodianExpansionCohort24BlindEntry = { anonymousId: string } & Pick<ZodianIdentityEditorialProfile, typeof FIELDS[number]>;
export const listZodianCanonicalIdentityExpansionCohort24V1BlindEntries = (): ZodianExpansionCohort24BlindEntry[] => ZODIAN_CANONICAL_IDENTITY_EXPANSION_COHORT_24_V1_BLIND_ENTRIES.map((anonymousId) => { const index = Number(anonymousId.slice(-2)) - 1; const p = ENTRIES.filter((entry) => entry.wave === "A")[index]!.profile!; return { anonymousId, ...Object.fromEntries(FIELDS.map((field) => [field, [...p[field]]])) } as ZodianExpansionCohort24BlindEntry; });
