import { validateZodianIdentityEditorialProfile, type ZodianIdentityEditorialProfile } from "./zodian-identity-editorial-layer-v1.ts";

export type ZodianExpansionProfileStatusV1 = "source_ready" | "editorial_review" | "approved" | "blocked";
export type ZodianExpansionProfileReviewEvidenceV1 = { sourceSupportReviewed?: boolean; fieldResponsibilityReviewed?: boolean; contradictionReviewed?: boolean; difficultTraitsReviewed?: boolean; blindLabelReviewComplete?: boolean; storyEngineUsefulnessReviewed?: boolean; humanApprovalComplete?: boolean; sourceLimitation?: string };
export type ZodianExpansionProfileLifecycleStateV1 = { status: ZodianExpansionProfileStatusV1; profile: ZodianIdentityEditorialProfile | null; reviewEvidence?: ZodianExpansionProfileReviewEvidenceV1 };
export type ZodianExpansionProfileLifecycleFindingV1 = { field: string; code: string; message: string };
const required = ["sourceSupportReviewed", "fieldResponsibilityReviewed", "contradictionReviewed", "difficultTraitsReviewed", "blindLabelReviewComplete", "storyEngineUsefulnessReviewed", "humanApprovalComplete"] as const;
const add = (findings: ZodianExpansionProfileLifecycleFindingV1[], field: string, code: string, message: string) => findings.push({ field, code, message });
export function validateZodianExpansionProfileLifecycleStateV1(state: ZodianExpansionProfileLifecycleStateV1): ZodianExpansionProfileLifecycleFindingV1[] { const findings: ZodianExpansionProfileLifecycleFindingV1[] = []; const evidence = state.reviewEvidence; if (state.status === "source_ready") { if (state.profile) add(findings, "profile", "source_ready_profile", "Source-ready state cannot expose a profile."); if (evidence?.humanApprovalComplete) add(findings, "reviewEvidence.humanApprovalComplete", "source_ready_approval", "Source-ready state cannot have approval evidence."); if (evidence?.sourceLimitation?.trim()) add(findings, "reviewEvidence.sourceLimitation", "source_ready_limitation", "Source-ready state cannot have a blocked-source limitation."); } if (state.status === "blocked") { if (state.profile) add(findings, "profile", "blocked_profile", "Blocked state cannot expose a profile."); if (!evidence?.sourceLimitation?.trim()) add(findings, "reviewEvidence.sourceLimitation", "blocked_without_limitation", "Blocked state needs a documented source limitation."); if (evidence?.humanApprovalComplete) add(findings, "reviewEvidence.humanApprovalComplete", "blocked_approval", "Blocked state cannot have approval evidence."); } if (state.status === "editorial_review" || state.status === "approved") { if (!state.profile) add(findings, "profile", "missing_profile", "A reviewed state needs a profile."); else for (const finding of validateZodianIdentityEditorialProfile(state.profile)) add(findings, finding.field, "invalid_profile", finding.message); } if (state.status === "editorial_review" && evidence?.humanApprovalComplete) add(findings, "reviewEvidence.humanApprovalComplete", "premature_approval", "Editorial review cannot be final-approved."); if (state.status === "approved") { for (const field of required) if (!evidence?.[field]) add(findings, `reviewEvidence.${field}`, "missing_approval_evidence", "Approved state needs complete review evidence."); if (evidence?.sourceLimitation?.trim()) add(findings, "reviewEvidence.sourceLimitation", "approved_limitation", "Approved state cannot be source-blocked."); } return findings; }
export function canTransitionZodianExpansionProfileStatusV1(current: ZodianExpansionProfileStatusV1, next: ZodianExpansionProfileLifecycleStateV1): boolean { if (validateZodianExpansionProfileLifecycleStateV1(next).length) return false; if (current === "approved") return false; if (current === "blocked") return false; if (current === "source_ready") return next.status === "editorial_review" || next.status === "blocked"; return next.status === "editorial_review" || next.status === "approved" || next.status === "blocked"; }
