import { sourceMayInformDistilledEditorialProfiles } from "./zodian-canonical-source-registry-v1.ts";

export const ZODIAN_CANONICAL_IDENTITY_COHORT_12_V1 = "zodian-canonical-identity-cohort-12-v1" as const;
export const ZODIAN_COHORT_12_SOURCE_ID = "source:suzanne-white:new-astrology-21st-century" as const;
export type ZodianCohort12Status = "source_ready" | "drafted" | "editorial_review" | "approved" | "blocked";
export type ZodianCohort12Entry = { identity: { westernSign: string; chineseSign: string }; status: ZodianCohort12Status; sourceId: typeof ZODIAN_COHORT_12_SOURCE_ID; sourcePath: string; sourceSectionLocated: boolean; rationale: string; contradictionToTest: string; profile: null };

const SOURCE_PATH = "project_sources/01-The-New-Astrology-for-the-21st-Century-Suzanne-White-.txt";
const ENTRIES: readonly ZodianCohort12Entry[] = Object.freeze([
  ["Libra","Snake","validated pilot; indirect influence versus firmer limits","warmth can become management"], ["Taurus","Horse","validated pilot; recognition versus reliability","ability can outrun trust"], ["Sagittarius","Monkey","validated pilot; purpose versus private gain","ambition can displace closeness"], ["Gemini","Dragon","validated pilot; novelty versus loyalty","attention can make pauses feel personal"],
  ["Aries","Rat","action-oriented contrast with strategic calculation","drive can conflict with social approval"], ["Pisces","Dog","reflective and guarded contrast","care can conflict with self-protection"], ["Leo","Horse","visible action and pride contrast","confidence can meet disappointment"], ["Aquarius","Snake","private, indirect social contrast","distance can coexist with influence"], ["Cancer","Pig","expressive care and control contrast","devotion can become excess or restraint"], ["Virgo","Dragon","analysis and force contrast","precision can collide with display"], ["Capricorn","Rooster","discipline and presentation contrast","order can become rigidity"], ["Scorpio","Dragon","intensity and power contrast","control can conflict with vulnerability"],
].map(([westernSign, chineseSign, rationale, contradictionToTest]) => Object.freeze({ identity: Object.freeze({ westernSign, chineseSign }), status: "source_ready" as const, sourceId: ZODIAN_COHORT_12_SOURCE_ID, sourcePath: SOURCE_PATH, sourceSectionLocated: true, rationale, contradictionToTest, profile: null })));

function clone(entry: ZodianCohort12Entry): ZodianCohort12Entry { return { ...entry, identity: { ...entry.identity } }; }
export function listZodianCanonicalIdentityCohort12V1(): ZodianCohort12Entry[] { return ENTRIES.map(clone); }
export function getZodianCanonicalIdentityCohort12V1(westernSign: string, chineseSign: string): ZodianCohort12Entry | undefined { const entry = ENTRIES.find((item) => item.identity.westernSign === westernSign && item.identity.chineseSign === chineseSign); return entry ? clone(entry) : undefined; }
export function validateZodianCanonicalIdentityCohort12V1(entries: readonly ZodianCohort12Entry[] = ENTRIES): string[] { const findings: string[] = []; const seen = new Set<string>(); if (entries.length !== 12) findings.push("incorrect cohort size"); for (const entry of entries) { const key = `${entry.identity.westernSign}\u0000${entry.identity.chineseSign}`; if (!entry.identity.westernSign || !entry.identity.chineseSign) findings.push("blank identity"); if (seen.has(key)) findings.push("duplicate identity"); seen.add(key); if (!(["source_ready","drafted","editorial_review","approved","blocked"] as string[]).includes(entry.status)) findings.push("unknown status"); if (!entry.sourceSectionLocated || !sourceMayInformDistilledEditorialProfiles(entry.sourceId)) findings.push("missing approved source readiness"); if (entry.profile !== null) findings.push("placeholder or populated profile not allowed in scaffold"); if (!entry.rationale || !entry.contradictionToTest) findings.push("missing cohort rationale"); } for (const key of ["Libra\u0000Snake","Taurus\u0000Horse","Sagittarius\u0000Monkey","Gemini\u0000Dragon"]) if (!seen.has(key)) findings.push("missing pilot identity"); return findings; }
