import { type ZodianIdentityEditorialProfile, validateZodianIdentityEditorialProfile } from "./zodian-identity-editorial-layer-v1.ts";
import { sourceMayInformDistilledEditorialProfiles, zodianCanonicalSourceExistsV1 } from "./zodian-canonical-source-registry-v1.ts";
import { listZodianCanonicalIdentityCohort12V1 } from "./zodian-canonical-identity-cohort-12-v1.ts";

export const ZODIAN_CANONICAL_IDENTITY_COHORT_12_V2 = "zodian-canonical-identity-cohort-12-v2" as const;
export const ZODIAN_COHORT_12_V2_SOURCE_ID = "source:suzanne-white:new-astrology-21st-century" as const;
export type ZodianCohort12V2Status = "source_ready" | "editorial_review" | "blocked";
export type ZodianCohort12V2Entry = { identity:{westernSign:string;chineseSign:string};status:ZodianCohort12V2Status;sourceId:typeof ZODIAN_COHORT_12_V2_SOURCE_ID;sourcePath:string;sourceSectionLocated:boolean;existingApprovedZodianRecord:false;readyForManualDistillation:boolean;sourceLimitationNote:string;replacementIdentity:null;structuralRiskTags:readonly string[];selectionRationale:string;nearestV1Comparison:{westernSign:string;chineseSign:string};profile:ZodianIdentityEditorialProfile|null };
export type ZodianCohort12V2Finding={field:string;code:string;message:string};
const SOURCE_PATH="project_sources/01-The-New-Astrology-for-the-21st-Century-Suzanne-White-.txt";
const FIELDS=["coreMotivations","recurringStrengths","recurringFriction","commonBlindSpots","interpersonalPatterns","emotionalPatterns"] as const;
const GENERIC=/\b(?:values honesty|cares about others|wants success|works hard|needs balance|can overthink|seeks stability|values independence|natural leader|struggles with trust|emotionally available|highly intuitive|deeply loyal)\b/i;
type Field=typeof FIELDS[number];
const p=(westernSign:string,chineseSign:string,fields:Record<Field,string[]>):ZodianIdentityEditorialProfile=>({version:"zodian-identity-editorial-layer-v1",identity:{westernSign,chineseSign},...fields,provenance:{sourceIds:[ZODIAN_COHORT_12_V2_SOURCE_ID]}});
const PROFILES:readonly ZodianIdentityEditorialProfile[]=Object.freeze([
p("Libra","Tiger",{coreMotivations:["Wants to impress and please while retaining independence."],recurringStrengths:["Draws followers through confidence and charisma.","Can apply sustained effort to chosen projects."],recurringFriction:["A sense of justice can conflict with impatience for rules."],commonBlindSpots:["May assume personal judgment outranks shared conventions."],interpersonalPatterns:["Leads and advises with warmth, force, and irreverence."],emotionalPatterns:["Can move quickly from charm to defiance when constrained."]}),
p("Taurus","Pig",{coreMotivations:["Seeks comfort, abundance, and a life arranged on personal terms."],recurringStrengths:["Combines practical force with careful, detailed work.","Protects close people through sustained material care."],recurringFriction:["Generosity can coexist with a strong need to direct the arrangement."],commonBlindSpots:["May give trust too completely once convinced of another person."],interpersonalPatterns:["Cooperates most easily when allowed a central say."],emotionalPatterns:["Worries intensely when unable to meet a commitment."]}),
p("Sagittarius","Sheep",{coreMotivations:["Seeks security for self and close people while pursuing large projects."],recurringStrengths:["Finds unusual solutions to difficult problems.","Sustains intricate creative work with unusual energy."],recurringFriction:["A need for protection can collide with adventurous enterprise."],commonBlindSpots:["May let the next undertaking override ordinary limits of time."],interpersonalPatterns:["Offers help when a problem appears to need solving."],emotionalPatterns:["Threats to security can unsettle an otherwise capable presentation."]}),
p("Gemini","Ox",{coreMotivations:["Seeks a settled life without giving up stimulating expression."],recurringStrengths:["Sustains concentration longer than a quick first impression suggests.","Uses dry storytelling to hold attention."],recurringFriction:["A deliberate pace can sit uneasily beside a restless, verbal mind."],commonBlindSpots:["May mistake an unassuming exterior for being overlooked."],interpersonalPatterns:["Draws others in through detailed, wry accounts rather than display."],emotionalPatterns:["Keeps feeling and humor understated rather than plainly announced."]}),
p("Aries","Ox",{coreMotivations:["Seeks tangible achievement through effort and force."],recurringStrengths:["Applies endurance to serious, practical problems.","Expresses capability most clearly through completed work."],recurringFriction:["Drive and strength can collide with difficulty communicating easily."],commonBlindSpots:["May dismiss social ease as superficial when it does not reward effort."],interpersonalPatterns:["Can seem reserved or forbidding despite a wish to contribute."],emotionalPatterns:["Disappointment with superficiality can harden into alienation."]}),
p("Pisces","Ox",{coreMotivations:["Seeks security, comfort, and respected standing among close people."],recurringStrengths:["Combines patience with strategic observation.","Uses stories and detail to make an impression."],recurringFriction:["Sensitivity can coexist with a calculated, slow-moving approach to conflict."],commonBlindSpots:["May turn grievance into indirect strategy rather than direct action."],interpersonalPatterns:["Maintains a select, devoted circle and expects mutual respect."],emotionalPatterns:["Can become jealous or resentful around betrayal and disrespect."]}),
p("Leo","Dog",{coreMotivations:["Seeks to defend people and causes that feel worth believing in."],recurringStrengths:["Keeps acting under pressure rather than retreating.","Brings warmth and candor to sustained responsibility."],recurringFriction:["Strong belief can coexist with a bleak view of other people."],commonBlindSpots:["May excuse harmful conduct when loyalty is engaged."],interpersonalPatterns:["Shows devotion through energetic advocacy and practical help."],emotionalPatterns:["Expects injustice and criticism, yet remains combative rather than defeated."]}),
p("Aquarius","Dragon",{coreMotivations:["Seeks control over direction while appearing proper and composed."],recurringStrengths:["Combines clear thinking with forceful organization.","Can persuade through varied forms of charm and argument."],recurringFriction:["A wish to please can conflict with an insistence on having things done one way."],commonBlindSpots:["May treat competition as a threat to be controlled."],interpersonalPatterns:["Builds followership through polish, favors, and persuasive pressure."],emotionalPatterns:["Maintains cool severity when challenged or contradicted."]}),
p("Cancer","Rat",{coreMotivations:["Seeks private refuge while also wanting a distinctive social presence."],recurringStrengths:["Uses wit and language to build a memorable personal world."],recurringFriction:["Withdrawal can alternate with a wish to host, impress, and gather people."],commonBlindSpots:["May confuse personal distinction with distance from ordinary choices."],interpersonalPatterns:["Moves between cultivated sociability and guarded solitude."],emotionalPatterns:["Can become possessive of a self-defined standard of excellence."]}),
p("Virgo","Cat",{coreMotivations:["Seeks progress and peace without unnecessary exposure to conflict."],recurringStrengths:["Works patiently on practical projects rather than empty talk."],recurringFriction:["Duty and advancement can conflict with a strong wish to retreat."],commonBlindSpots:["May sacrifice what matters to avoid confrontation."],interpersonalPatterns:["Tolerates others while keeping emotional and social distance."],emotionalPatterns:["Human contact can produce unease beneath controlled manners."]}),
p("Capricorn","Monkey",{coreMotivations:["Seeks order and serious presentation while protecting a playful private side."],recurringStrengths:["Uses timing, wit, and expression with precision."],recurringFriction:["Public gravity can conflict with a sly, unruly private impulse."],commonBlindSpots:["May turn private responsibility into excessive control of others."],interpersonalPatterns:["Presents formally in public but becomes sharp and theatrical in trusted settings."],emotionalPatterns:["A smooth exterior can coexist with persistent private unease."]}),
p("Scorpio","Horse",{coreMotivations:["Seeks independence, impact, and room for unconventional ideas."],recurringStrengths:["Carries demanding projects through with energy and directness."],recurringFriction:["Strong individualism can conflict with feeling deeply affected by surroundings."],commonBlindSpots:["May mistake ruthless determination for a complete answer."],interpersonalPatterns:["Speaks directly and uses satire without softening the point."],emotionalPatterns:["Early anxiety can give way to forceful self-direction."]}),
]);
const SELECTED=[
["Libra","Tiger",["direct-versus-indirect style","comparison-risk"],"Tests a socially forceful counterpart to the v1 rapport/control record.",["Libra","Snake"]],["Taurus","Pig",["security-versus-indulgence","warmth-risk"],"Tests a security-oriented combination without reusing the v1 talent/recognition structure.",["Cancer","Pig"]],["Sagittarius","Sheep",["subtle-contradiction","emotional-grounding"],"Tests whether a less overtly dominant selection can sustain source-grounded tension.",["Pisces","Dog"]],["Gemini","Ox",["stability-versus-novelty","category-ambiguity"],"Tests a possible v1 novelty comparison under a more restrained structural setup.",["Gemini","Dragon"]],["Aries","Ox",["dominance-risk","difficult-trait-integrity"],"Tests an assertive selection where strength and control may be easy to blur.",["Aries","Rat"]],["Pisces","Ox",["security-orientation","emotional-grounding"],"Tests overlap risk with v1 guarded sensitivity without assuming the same source structure.",["Pisces","Dog"]],["Leo","Dog",["warmth-versus-guardedness","over-flattering-risk"],"Tests a socially warm selection that may be made too admirable without source restraint.",["Leo","Horse"]],["Aquarius","Dragon",["indirect-versus-dominant","comparison-risk"],"Tests a possible overlap with v1 private freedom while requiring a distinct combined structure.",["Aquarius","Snake"]],["Cancer","Rat",["care-versus-control","relationship-example-risk"],"Tests whether familiar care/control territory is genuinely distinct from the v1 reference.",["Cancer","Pig"]],["Virgo","Cat",["subtle-contradiction","career-example-risk"],"Tests a less forceful Virgo comparison and category separation under quieter source evidence.",["Virgo","Dragon"]],["Capricorn","Monkey",["ambition-versus-emotion","overlap-risk"],"Tests a possible v1 mission/authority resemblance without presuming shared traits.",["Sagittarius","Monkey"]],["Scorpio","Horse",["expressive-versus-restrained","difficult-trait-integrity"],"Tests a high-intensity selection against the v1 command/vulnerability reference.",["Scorpio","Dragon"]],
] as const;
const ENTRIES:readonly ZodianCohort12V2Entry[]=Object.freeze(SELECTED.map(([westernSign,chineseSign,structuralRiskTags,selectionRationale,nearest])=>Object.freeze({identity:Object.freeze({westernSign,chineseSign}),status:"editorial_review" as const,sourceId:ZODIAN_COHORT_12_V2_SOURCE_ID,sourcePath:SOURCE_PATH,sourceSectionLocated:true,existingApprovedZodianRecord:false as const,readyForManualDistillation:true,sourceLimitationNote:"Combined-sign section reviewed; profiles remain pending final human approval.",replacementIdentity:null,structuralRiskTags:Object.freeze([...structuralRiskTags]),selectionRationale,nearestV1Comparison:Object.freeze({westernSign:nearest[0],chineseSign:nearest[1]}),profile:PROFILES.find((item)=>item.identity.westernSign===westernSign&&item.identity.chineseSign===chineseSign)!})));
const key=(identity:{westernSign:string;chineseSign:string})=>`${identity.westernSign}\u0000${identity.chineseSign}`; const normal=(note:string)=>note.toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
function cloneProfile(profile:ZodianIdentityEditorialProfile):ZodianIdentityEditorialProfile{return {...profile,identity:{...profile.identity},coreMotivations:[...profile.coreMotivations],recurringStrengths:[...profile.recurringStrengths],recurringFriction:[...profile.recurringFriction],commonBlindSpots:[...profile.commonBlindSpots],interpersonalPatterns:[...profile.interpersonalPatterns],emotionalPatterns:[...profile.emotionalPatterns],provenance:{sourceIds:[...profile.provenance!.sourceIds]}};}
function clone(entry:ZodianCohort12V2Entry):ZodianCohort12V2Entry{return {...entry,identity:{...entry.identity},structuralRiskTags:[...entry.structuralRiskTags],nearestV1Comparison:{...entry.nearestV1Comparison},profile:entry.profile&&cloneProfile(entry.profile)};}
export function listZodianCanonicalIdentityCohort12V2(){return ENTRIES.map(clone)} export function getZodianCanonicalIdentityCohort12V2(westernSign:string,chineseSign:string){const e=ENTRIES.find((item)=>item.identity.westernSign===westernSign&&item.identity.chineseSign===chineseSign);return e&&clone(e)} export function listBlockedZodianCanonicalIdentityCohort12V2(){return ENTRIES.filter((e)=>e.status==="blocked").map(clone)};
export function validateZodianCanonicalIdentityCohort12V2(entries:readonly ZodianCohort12V2Entry[]=ENTRIES):ZodianCohort12V2Finding[]{const findings:ZodianCohort12V2Finding[]=[];const seen=new Set<string>(),notes=new Map<string,string>(),v1=new Set(listZodianCanonicalIdentityCohort12V1().map((e)=>key(e.identity)));const add=(field:string,code:string,message:string)=>findings.push({field,code,message});if(entries.length!==12)add("cohort","incorrect_size","Cohort must contain twelve identities.");for(const entry of entries){const k=key(entry.identity);if(seen.has(k))add("identity","duplicate_identity","Duplicate identity.");seen.add(k);if(v1.has(k))add("identity","reused_v1_identity","v2 cannot reuse v1 identity.");if(!["editorial_review","blocked"].includes(entry.status))add("status","invalid_status","Only editorial_review or blocked is allowed.");if(!entry.sourceSectionLocated||!entry.readyForManualDistillation||!zodianCanonicalSourceExistsV1(entry.sourceId)||!sourceMayInformDistilledEditorialProfiles(entry.sourceId))add("source","invalid_source_readiness","Approved source readiness is required.");if(entry.status==="blocked"&&entry.profile)add("profile","blocked_profile","Blocked identity cannot expose a profile.");if(!entry.profile){if(entry.status!=="blocked")add("profile","missing_profile","Non-blocked entry needs a profile.");continue;}if(entry.profile.identity.westernSign!==entry.identity.westernSign||entry.profile.identity.chineseSign!==entry.identity.chineseSign)add("profile.identity","identity_mismatch","Profile identity differs.");for(const f of validateZodianIdentityEditorialProfile(entry.profile))add(f.field,"invalid_profile",f.message);const local=new Set<string>();for(const field of FIELDS){const array=entry.profile[field];if(array.length<1||array.length>4)add(field,"note_count","Category needs one to four notes.");for(const note of array){const n=normal(note);if(GENERIC.test(note))add(field,"generic_tripwire","Generic wording needs review.");if(local.has(n))add(field,"same_profile_duplicate","Duplicate across profile fields.");local.add(n);if(notes.has(n))add(field,"normalized_duplicate",`Duplicates ${notes.get(n)}.`);else notes.set(n,`${k}.${field}`)}}}return findings;}
export const ZODIAN_CANONICAL_IDENTITY_COHORT_12_V2_BLIND_ENTRIES=Object.freeze(["cohort-v2-08","cohort-v2-03","cohort-v2-11","cohort-v2-01","cohort-v2-09","cohort-v2-05","cohort-v2-12","cohort-v2-02","cohort-v2-10","cohort-v2-04","cohort-v2-07","cohort-v2-06"]);
