import { type ZodianIdentityEditorialProfile, validateZodianIdentityEditorialProfile } from "./zodian-identity-editorial-layer-v1.ts";
import { sourceMayInformDistilledEditorialProfiles, zodianCanonicalSourceExistsV1 } from "./zodian-canonical-source-registry-v1.ts";

export const ZODIAN_CANONICAL_IDENTITY_COHORT_12_V1 = "zodian-canonical-identity-cohort-12-v1" as const;
export const ZODIAN_COHORT_12_SOURCE_ID = "source:suzanne-white:new-astrology-21st-century" as const;
export type ZodianCohort12Status = "source_ready" | "drafted" | "editorial_review" | "approved" | "blocked";
export type ZodianCohort12Entry = { identity: { westernSign: string; chineseSign: string }; status: ZodianCohort12Status; sourceId: typeof ZODIAN_COHORT_12_SOURCE_ID; sourcePath: string; sourceSectionLocated: boolean; rationale: string; contradictionToTest: string; reviewState: "editorial_review" | "approved" | "blocked"; approvalEvidence?: string; profile: ZodianIdentityEditorialProfile | null };
export type ZodianCohort12Finding = { field: string; code: string; message: string };

const SOURCE_PATH = "project_sources/01-The-New-Astrology-for-the-21st-Century-Suzanne-White-.txt";
const FIELDS = ["coreMotivations", "recurringStrengths", "recurringFriction", "commonBlindSpots", "interpersonalPatterns", "emotionalPatterns"] as const;
const PLACEHOLDER = /\b(?:todo|tbd|placeholder|fill me|unknown)\b/i;
const GENERIC = /\b(?:values honesty|cares about others|wants success|works hard|needs balance|can overthink|seeks stability|values independence|is a natural leader|struggles with trust)\b/i;
type Field = typeof FIELDS[number];

function profile(westernSign: string, chineseSign: string, fields: Record<Field, string[]>): ZodianIdentityEditorialProfile {
  return { version: "zodian-identity-editorial-layer-v1", identity: { westernSign, chineseSign }, ...fields, provenance: { sourceIds: [ZODIAN_COHORT_12_SOURCE_ID] } };
}

// The first four records intentionally retain the latest approved pilot wording.
const PROFILES: readonly ZodianIdentityEditorialProfile[] = Object.freeze([
  profile("Libra", "Snake", { coreMotivations:["Seeks influence through rapport rather than force.","Wants admiration and comfort while keeping influence indirect."], recurringStrengths:["Reads what will make an audience feel included.","Turns difficult differences into calm appeals."], recurringFriction:["Comfort and indulgence can compete with follow-through.","Wants leadership without the strain of open conflict."], commonBlindSpots:["Charm can obscure when a firmer boundary is needed.","Generosity of attention can become managing everyone."], interpersonalPatterns:["Builds loyalty through warmth, tact, and visible care.","Guides groups by persuasion rather than rank."], emotionalPatterns:["Can drift toward comfort when ordinary demands feel dull.","Feels pulled between caring for others and protecting personal comfort."] }),
  profile("Taurus", "Horse", { coreMotivations:["Wants visible proof that ability has weight.","Seeks a life that feels both exceptional and secure."], recurringStrengths:["Brings discipline and high standards to a chosen craft.","Pairs practical follow-through with strong instincts."], recurringFriction:["Confidence in talent can resist ordinary social effort.","Desire for recognition can compete with ordinary social effort."], commonBlindSpots:["May mistake being overlooked for being undervalued.","May wait for special regard while avoiding ordinary social effort."], interpersonalPatterns:["Keeps private matters guarded while caring about public regard.","Responds best to respect for ability without constant praise."], emotionalPatterns:["Feels steadier when effort is recognized.","Can become withdrawn or irritable when feeling misunderstood."] }),
  profile("Sagittarius", "Monkey", { coreMotivations:["Wants influence that advances a large purpose.","Seeks independence, leverage, and a place near decisions."], recurringStrengths:["Organizes large aims into clear action.","Makes a convincing case without open confrontation."], recurringFriction:["Public ambition can conflict with emotional closeness.","Long-range goals can outweigh the demands of closeness."], commonBlindSpots:["May treat intimacy as a threat to independence.","May hide self-interest behind a larger mission."], interpersonalPatterns:["Uses timing, competence, and persuasion to build authority.","Keeps a lighter, playful side for trusted company."], emotionalPatterns:["Keeps emotional obligations secondary to larger aims."] }),
  profile("Gemini", "Dragon", { coreMotivations:["Seeks momentum, attention, and the thrill of a new possibility.","Wants close bonds to feel vivid and unmistakably loyal."], recurringStrengths:["Generates contagious ideas and gathers people around them.","Rallies energy quickly when a situation needs a spark."], recurringFriction:["Craves novelty yet resists the sustained work behind a plan.","Strong need for attention can conflict with another person's spotlight."], commonBlindSpots:["May confuse a bold first move with durable commitment.","May read ordinary distance as a loss of loyalty."], interpersonalPatterns:["Uses presence, humor, and confidence to draw attention.","Shows fierce care for close people while asking a lot of them."], emotionalPatterns:["Reacts intensely to rejection, failure, or feeling overlooked.","A commanding front can hide a more easily wounded core."] }),
  profile("Aries", "Rat", { coreMotivations:["Seeks visible achievement and a busy life.","Wants authority without social isolation."], recurringStrengths:["Moves quickly from ideas into organized plans.","Combines boldness with social charm."], recurringFriction:["Ambition collides with discomfort about being disliked.","Urgency can turn many plans into restless pressure."], commonBlindSpots:["May hold others to standards not applied personally.","May treat idleness as a character flaw."], interpersonalPatterns:["Offers energetic help while expecting effort in return.","Can become critical of close people who disappoint."], emotionalPatterns:["A calm presentation can cover persistent nervousness.","Becomes edgy when events slow down."] }),
  profile("Pisces", "Dog", { coreMotivations:["Seeks safety, duty, and a dependable bond.","Wants protection from uncertainty more than public distinction."], recurringStrengths:["Combines close observation with dry humor.","Shows persistence when responsibility is involved."], recurringFriction:["Tender feeling conflicts with a guarded defensive stance.","Duty can outweigh a fragile capacity for strain."], commonBlindSpots:["May see danger before there is enough evidence.","May avoid new people to preserve calm."], interpersonalPatterns:["Shows care through reliability and discretion.","Uses sarcasm when feeling exposed or worried."], emotionalPatterns:["Worry gathers behind a restrained exterior.","Criticism can land with disproportionate force."] }),
  profile("Leo", "Horse", { coreMotivations:["Seeks freedom, admiration, and a vivid life.","Wants to lead without feeling contained."], recurringStrengths:["Brings confident presence and quick initiative.","Can act decisively when others hesitate."], recurringFriction:["Pride and independence can clash with emotional dependence.","A need for excitement can resist ordinary limits."], commonBlindSpots:["May assume confidence and good intentions make a plan viable.","May mistake intensity for lasting devotion."], interpersonalPatterns:["Draws attention through flair and self-assurance.","Can swing between distance and total absorption in love."], emotionalPatterns:["Criticism and setbacks can prompt a forceful response."] }),
  profile("Aquarius", "Snake", { coreMotivations:["Seeks freedom for imagination and private plans.","Wants to help without being controlled or displayed."], recurringStrengths:["Combines unusual ideas with practical kindness.","Reads timing and possibilities with unusual precision."], recurringFriction:["Private freedom can conflict with obligations to others.","Reason can take precedence over admitted feeling."], commonBlindSpots:["May escape into imagination when facts become inconvenient.","May treat secrecy as harmless social maneuvering."], interpersonalPatterns:["Helps generously while revealing little of the self.","Keeps influence indirect and resists formal authority."], emotionalPatterns:["Filters feeling through thought before showing it.","Can become jealous while insisting on personal freedom."] }),
  profile("Cancer", "Pig", { coreMotivations:["Seeks a protected, abundant home and loyal circle.","Wants to care for innocence and preserve what feels precious."], recurringStrengths:["Offers serious devotion and material generosity.","Brings patience and conviction to long commitments."], recurringFriction:["Deep care can become a need to direct others.","Reserve can coexist with forceful certainty."], commonBlindSpots:["May mistake devotion for permission to interfere.","May assume the preferred way is the only sound way."], interpersonalPatterns:["Shows affection through giving, hosting, and protection.","Can make close people feel loved and managed at once."], emotionalPatterns:["Holds feeling back until crossed, then reacts intensely.","Can retreat into sulking after disappointment."] }),
  profile("Virgo", "Dragon", { coreMotivations:["Seeks mastery, impact, and visible competence.","Wants order while needing room for forceful expression."], recurringStrengths:["Combines precision with bold drive.","Can spot flaws quickly and pursue correction relentlessly."], recurringFriction:["High standards collide with a volatile response to error.","A wish to be impressive conflicts with fear of failure."], commonBlindSpots:["May turn a small mistake into a verdict on the self.","May overlook how forceful criticism lands on others."], interpersonalPatterns:["Takes charge through correction and strong opinions.","Can repel allies while trying to improve the situation."], emotionalPatterns:["Irritation rises quickly around failure or disorder.","Pride makes vulnerability difficult to show."] }),
  profile("Capricorn", "Rooster", { coreMotivations:["Seeks accomplishment, propriety, and favorable judgment.","Wants respect for standards, effort, and judgment."], recurringStrengths:["Presents with polish and broad accomplishment."], recurringFriction:["Control and polish can crowd out flexibility.","Public certainty can conflict with private insecurity."], commonBlindSpots:["May treat a different method as a lesser one.","May confuse recognition with proof of worth."], interpersonalPatterns:["Shows care through responsibility and exacting support.","Can become critical when others ignore established standards."], emotionalPatterns:["Keeps anxiety behind competence and ceremony.","Becomes rigid when respect feels uncertain."] }),
  profile("Scorpio", "Dragon", { coreMotivations:["Seeks influence, victory, and deep recognition.","Wants power without surrendering emotional control."], recurringStrengths:["Pairs courage with cunning.","Can recover forcefully after major setbacks."], recurringFriction:["Ambition can collide with a need to be admired.","Control conflicts with jealousy and emotional exposure."], commonBlindSpots:["May set a larger goal than current limits allow.","May mistake homage for genuine loyalty."], interpersonalPatterns:["Uses charm and intensity to command a room.","Tests closeness while guarding the vulnerable core."], emotionalPatterns:["Jealousy can surface beneath a self-possessed front."] }),
]);

const DESCRIPTORS = [
  ["Libra","Snake","validated pilot; indirect influence versus firmer limits","warmth can become management"], ["Taurus","Horse","validated pilot; recognition versus reliability","ability can outrun trust"], ["Sagittarius","Monkey","validated pilot; purpose versus private gain","ambition can displace closeness"], ["Gemini","Dragon","validated pilot; novelty versus loyalty","attention can make pauses feel personal"],
  ["Aries","Rat","source section reviewed; drive and social calculation","power can conflict with approval"], ["Pisces","Dog","source section reviewed; tenderness and duty","care can become defensive worry"], ["Leo","Horse","source section reviewed; pride and freedom","confidence can become dependence"], ["Aquarius","Snake","source section reviewed; imagination and discretion","freedom can evade obligation"], ["Cancer","Pig","source section reviewed; devotion and abundance","care can become control"], ["Virgo","Dragon","source section reviewed; precision and force","mastery can become self-punishment"], ["Capricorn","Rooster","source section reviewed; discipline and display","order can become rigidity"], ["Scorpio","Dragon","source section reviewed; intensity and ambition","power can expose vulnerability"],
] as const;
const ENTRIES: readonly ZodianCohort12Entry[] = Object.freeze(DESCRIPTORS.map(([westernSign, chineseSign, rationale, contradictionToTest]) => Object.freeze({ identity: Object.freeze({ westernSign, chineseSign }), status: "approved" as const, sourceId: ZODIAN_COHORT_12_SOURCE_ID, sourcePath: SOURCE_PATH, sourceSectionLocated: true, rationale, contradictionToTest, reviewState: "approved" as const, approvalEvidence: "final-human-review: cohort-amendment-v1", profile: PROFILES.find((item) => item.identity.westernSign === westernSign && item.identity.chineseSign === chineseSign)! })));

function cloneProfile(profile: ZodianIdentityEditorialProfile): ZodianIdentityEditorialProfile { return { ...profile, identity: { ...profile.identity }, coreMotivations:[...profile.coreMotivations], recurringStrengths:[...profile.recurringStrengths], recurringFriction:[...profile.recurringFriction], commonBlindSpots:[...profile.commonBlindSpots], interpersonalPatterns:[...profile.interpersonalPatterns], emotionalPatterns:[...profile.emotionalPatterns], provenance: profile.provenance ? { sourceIds:[...profile.provenance.sourceIds] } : undefined }; }
function clone(entry: ZodianCohort12Entry): ZodianCohort12Entry { return { ...entry, identity:{...entry.identity}, profile: entry.profile && cloneProfile(entry.profile) }; }
function key(identity: { westernSign: string; chineseSign: string }) { return `${identity.westernSign}\u0000${identity.chineseSign}`; }
function normalize(note: string) { return note.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim(); }

export function listZodianCanonicalIdentityCohort12V1(): ZodianCohort12Entry[] { return ENTRIES.map(clone); }
export function getZodianCanonicalIdentityCohort12V1(westernSign: string, chineseSign: string): ZodianCohort12Entry | undefined { const entry = ENTRIES.find((item) => item.identity.westernSign === westernSign && item.identity.chineseSign === chineseSign); return entry && clone(entry); }
export function listCompletedZodianCanonicalIdentityCohort12V1(): ZodianCohort12Entry[] { return ENTRIES.filter((entry) => entry.profile !== null).map(clone); }
export function listBlockedZodianCanonicalIdentityCohort12V1(): ZodianCohort12Entry[] { return ENTRIES.filter((entry) => entry.status === "blocked").map(clone); }

/** A deterministic audit: generic wording is reported, never rejected by itself. */
export function validateZodianCanonicalIdentityCohort12V1(entries: readonly ZodianCohort12Entry[] = ENTRIES): ZodianCohort12Finding[] {
  const findings: ZodianCohort12Finding[] = []; const seen = new Set<string>(); const allNotes = new Map<string,string>();
  const add=(field:string,code:string,message:string)=>findings.push({field,code,message});
  if (entries.length !== 12) add("cohort","incorrect_size","The cohort must contain exactly twelve identities.");
  for (const entry of entries) { const identityKey=key(entry.identity); if (seen.has(identityKey)) add("identity","duplicate_identity","Duplicate identity."); seen.add(identityKey);
    if (!entry.sourceSectionLocated || !zodianCanonicalSourceExistsV1(entry.sourceId)) add("sourceId","unknown_provenance_source","Provenance source does not exist.");
    if (!sourceMayInformDistilledEditorialProfiles(entry.sourceId)) add("sourceId","unapproved_provenance_source","Source is not approved for distilled profiles.");
    if (entry.status === "approved" && (entry.reviewState !== "approved" || !entry.approvalEvidence?.trim())) add("status","approved_without_review","Approved status lacks completed final human-review evidence.");
    if (entry.status === "blocked" && entry.profile) add("profile","blocked_profile","Blocked identities cannot expose a profile.");
    if (!entry.profile) { if (entry.status !== "blocked") add("profile","missing_profile","Non-blocked entry needs a profile."); continue; }
    if (entry.profile.identity.westernSign !== entry.identity.westernSign || entry.profile.identity.chineseSign !== entry.identity.chineseSign) add("profile.identity","identity_mismatch","Profile identity differs from cohort identity.");
    for (const finding of validateZodianIdentityEditorialProfile(entry.profile)) add(finding.field,"invalid_editorial_profile",finding.message);
    const local = new Set<string>();
    for (const field of FIELDS) { const notes=entry.profile[field]; if (notes.length < 1 || notes.length > 4) add(field,"note_count_out_of_bounds","Each category must contain one to four notes.");
      for (const note of notes) { const normalized=normalize(note); if (PLACEHOLDER.test(note)) add(field,"placeholder_note","Placeholder language is not allowed."); if (GENERIC.test(note)) add(field,"generic_note_tripwire","Generic language needs human review."); if (local.has(normalized)) add(field,"same_profile_cross_field_duplicate","Duplicate note within profile."); local.add(normalized); if (allNotes.has(normalized)) add(field,"normalized_duplicate_note",`Duplicates ${allNotes.get(normalized)}.`); else allNotes.set(normalized,`${key(entry.identity)}.${field}`); }
    }
  } return findings;
}
