import { sourceMayInformDistilledEditorialProfiles, zodianCanonicalSourceExistsV1 } from "./zodian-canonical-source-registry-v1.ts";
import { listZodianCanonicalIdentityCohort12V1 } from "./zodian-canonical-identity-cohort-12-v1.ts";

export const ZODIAN_CANONICAL_IDENTITY_COHORT_12_V2 = "zodian-canonical-identity-cohort-12-v2" as const;
export const ZODIAN_COHORT_12_V2_SOURCE_ID = "source:suzanne-white:new-astrology-21st-century" as const;
export type ZodianCohort12V2Status = "source_ready" | "blocked";
export type ZodianCohort12V2Entry = { identity: { westernSign: string; chineseSign: string }; status: ZodianCohort12V2Status; sourceId: typeof ZODIAN_COHORT_12_V2_SOURCE_ID; sourcePath: string; sourceSectionLocated: boolean; existingApprovedZodianRecord: false; readyForManualDistillation: boolean; sourceLimitationNote: string; replacementIdentity: null; structuralRiskTags: readonly string[]; selectionRationale: string; nearestV1Comparison: { westernSign: string; chineseSign: string }; profile: null };
export type ZodianCohort12V2Finding = { field: string; code: string; message: string };

const SOURCE_PATH = "project_sources/01-The-New-Astrology-for-the-21st-Century-Suzanne-White-.txt";
const SELECTED = [
  ["Libra", "Tiger", ["direct-versus-indirect style", "comparison-risk"], "Tests a socially forceful counterpart to the v1 rapport/control record.", ["Libra", "Snake"]],
  ["Taurus", "Pig", ["security-versus-indulgence", "warmth-risk"], "Tests a security-oriented combination without reusing the v1 talent/recognition structure.", ["Cancer", "Pig"]],
  ["Sagittarius", "Sheep", ["subtle-contradiction", "emotional-grounding"], "Tests whether a less overtly dominant selection can sustain source-grounded tension.", ["Pisces", "Dog"]],
  ["Gemini", "Ox", ["stability-versus-novelty", "category-ambiguity"], "Tests a possible v1 novelty comparison under a more restrained structural setup.", ["Gemini", "Dragon"]],
  ["Aries", "Ox", ["dominance-risk", "difficult-trait-integrity"], "Tests an assertive selection where strength and control may be easy to blur.", ["Aries", "Rat"]],
  ["Pisces", "Ox", ["security-orientation", "emotional-grounding"], "Tests overlap risk with v1 guarded sensitivity without assuming the same source structure.", ["Pisces", "Dog"]],
  ["Leo", "Dog", ["warmth-versus-guardedness", "over-flattering-risk"], "Tests a socially warm selection that may be made too admirable without source restraint.", ["Leo", "Horse"]],
  ["Aquarius", "Dragon", ["indirect-versus-dominant", "comparison-risk"], "Tests a possible overlap with v1 private freedom while requiring a distinct combined structure.", ["Aquarius", "Snake"]],
  ["Cancer", "Rat", ["care-versus-control", "relationship-example-risk"], "Tests whether familiar care/control territory is genuinely distinct from the v1 reference.", ["Cancer", "Pig"]],
  ["Virgo", "Cat", ["subtle-contradiction", "career-example-risk"], "Tests a less forceful Virgo comparison and category separation under quieter source evidence.", ["Virgo", "Dragon"]],
  ["Capricorn", "Monkey", ["ambition-versus-emotion", "overlap-risk"], "Tests a possible v1 mission/authority resemblance without presuming shared traits.", ["Sagittarius", "Monkey"]],
  ["Scorpio", "Horse", ["expressive-versus-restrained", "difficult-trait-integrity"], "Tests a high-intensity selection against the v1 command/vulnerability reference.", ["Scorpio", "Dragon"]],
] as const;
const ENTRIES: readonly ZodianCohort12V2Entry[] = Object.freeze(SELECTED.map(([westernSign, chineseSign, structuralRiskTags, selectionRationale, nearest]) => Object.freeze({ identity: Object.freeze({ westernSign, chineseSign }), status: "source_ready" as const, sourceId: ZODIAN_COHORT_12_V2_SOURCE_ID, sourcePath: SOURCE_PATH, sourceSectionLocated: true, existingApprovedZodianRecord: false as const, readyForManualDistillation: true, sourceLimitationNote: "Combined-sign section located; trait support has not yet been reviewed.", replacementIdentity: null, structuralRiskTags: Object.freeze([...structuralRiskTags]), selectionRationale, nearestV1Comparison: Object.freeze({ westernSign: nearest[0], chineseSign: nearest[1] }), profile: null })));
function clone(entry: ZodianCohort12V2Entry): ZodianCohort12V2Entry { return { ...entry, identity:{...entry.identity}, structuralRiskTags:[...entry.structuralRiskTags], nearestV1Comparison:{...entry.nearestV1Comparison} }; }
const key = (identity: { westernSign: string; chineseSign: string }) => `${identity.westernSign}\u0000${identity.chineseSign}`;
export function listZodianCanonicalIdentityCohort12V2(): ZodianCohort12V2Entry[] { return ENTRIES.map(clone); }
export function getZodianCanonicalIdentityCohort12V2(westernSign: string, chineseSign: string): ZodianCohort12V2Entry | undefined { const entry = ENTRIES.find((item) => item.identity.westernSign === westernSign && item.identity.chineseSign === chineseSign); return entry && clone(entry); }
export function validateZodianCanonicalIdentityCohort12V2(entries: readonly ZodianCohort12V2Entry[] = ENTRIES): ZodianCohort12V2Finding[] { const findings: ZodianCohort12V2Finding[]=[]; const seen=new Set<string>(); const v1=new Set(listZodianCanonicalIdentityCohort12V1().map((entry)=>key(entry.identity))); const add=(field:string,code:string,message:string)=>findings.push({field,code,message}); if(entries.length!==12)add("cohort","incorrect_size","Cohort must contain twelve identities."); for(const entry of entries){const identityKey=key(entry.identity); if(!entry.identity.westernSign||!entry.identity.chineseSign)add("identity","blank_identity","Identity labels are required."); if(seen.has(identityKey))add("identity","duplicate_identity","Duplicate v2 identity."); seen.add(identityKey); if(v1.has(identityKey))add("identity","reused_v1_identity","v2 cannot reuse v1 identity."); if(!["source_ready","blocked"].includes(entry.status))add("status","unknown_status","Only source_ready or blocked is allowed before authoring."); if(!entry.sourceSectionLocated||!entry.readyForManualDistillation)add("source","missing_source_readiness","Source readiness is required."); if(!zodianCanonicalSourceExistsV1(entry.sourceId))add("sourceId","unknown_provenance_source","Unknown source."); if(!sourceMayInformDistilledEditorialProfiles(entry.sourceId))add("sourceId","unapproved_provenance_source","Source is not approved."); if(entry.profile!==null)add("profile","profile_present_in_scaffold","Profiles cannot exist at scaffold stage."); if(!entry.selectionRationale||entry.structuralRiskTags.length===0)add("selection","missing_structural_rationale","Selection requires structural risks and rationale."); if(!v1.has(key(entry.nearestV1Comparison)))add("comparison","unknown_v1_comparison","Comparison target must be in v1."); } return findings; }

/** Anonymous entries intentionally contain neither labels nor profile traits. */
export const ZODIAN_CANONICAL_IDENTITY_COHORT_12_V2_BLIND_IDS = Object.freeze(["cohort-v2-01","cohort-v2-02","cohort-v2-03","cohort-v2-04","cohort-v2-05","cohort-v2-06","cohort-v2-07","cohort-v2-08","cohort-v2-09","cohort-v2-10","cohort-v2-11","cohort-v2-12"]);
