import Foundation

enum FamousPatternData {
    static let exactMatches: [FamousPattern] = [
        FamousPattern(name: "Robert Downey Jr", western: .aries, chinese: .snake, line: "Exact famous match"),
        FamousPattern(name: "Emma Watson", western: .aries, chinese: .horse, line: "Exact famous match"),
        FamousPattern(name: "Sarah Jessica Parker", western: .aries, chinese: .snake, line: "Exact famous match"),
        FamousPattern(name: "Mariah Carey", western: .aries, chinese: .rooster, line: "Exact famous match"),
        FamousPattern(name: "Reese Witherspoon", western: .aries, chinese: .dragon, line: "Exact famous match"),
        FamousPattern(name: "Celine Dion", western: .aries, chinese: .monkey, line: "Exact famous match"),
        FamousPattern(name: "Jennifer Garner", western: .aries, chinese: .rat, line: "Exact famous match"),
        FamousPattern(name: "Keira Knightley", western: .aries, chinese: .ox, line: "Exact famous match"),

        FamousPattern(name: "Adele", western: .taurus, chinese: .dragon, line: "Exact famous match"),
        FamousPattern(name: "David Beckham", western: .taurus, chinese: .rabbit, line: "Exact famous match"),
        FamousPattern(name: "George Clooney", western: .taurus, chinese: .ox, line: "Exact famous match"),
        FamousPattern(name: "Janet Jackson", western: .taurus, chinese: .horse, line: "Exact famous match"),
        FamousPattern(name: "Cher", western: .taurus, chinese: .dog, line: "Exact famous match"),
        FamousPattern(name: "Dwayne Johnson", western: .taurus, chinese: .rat, line: "Exact famous match"),
        FamousPattern(name: "Gigi Hadid", western: .taurus, chinese: .pig, line: "Exact famous match"),
        FamousPattern(name: "Queen Elizabeth II", western: .taurus, chinese: .tiger, line: "Exact famous match"),

        FamousPattern(name: "Angelina Jolie", western: .gemini, chinese: .rabbit, line: "Exact famous match"),
        FamousPattern(name: "Johnny Depp", western: .gemini, chinese: .rabbit, line: "Exact famous match"),
        FamousPattern(name: "Natalie Portman", western: .gemini, chinese: .rooster, line: "Exact famous match"),
        FamousPattern(name: "Kendrick Lamar", western: .gemini, chinese: .rabbit, line: "Exact famous match"),
        FamousPattern(name: "Paul McCartney", western: .gemini, chinese: .horse, line: "Exact famous match"),
        FamousPattern(name: "Marilyn Monroe", western: .gemini, chinese: .tiger, line: "Exact famous match"),
        FamousPattern(name: "Morgan Freeman", western: .gemini, chinese: .ox, line: "Exact famous match"),
        FamousPattern(name: "Nicole Kidman", western: .gemini, chinese: .goat, line: "Exact famous match"),

        FamousPattern(name: "Ariana Grande", western: .cancer, chinese: .rooster, line: "Exact famous match"),
        FamousPattern(name: "Selena Gomez", western: .cancer, chinese: .monkey, line: "Exact famous match"),
        FamousPattern(name: "Tom Hanks", western: .cancer, chinese: .monkey, line: "Exact famous match"),
        FamousPattern(name: "Meryl Streep", western: .cancer, chinese: .ox, line: "Exact famous match"),
        FamousPattern(name: "Kevin Hart", western: .cancer, chinese: .goat, line: "Exact famous match"),
        FamousPattern(name: "Pamela Anderson", western: .cancer, chinese: .goat, line: "Exact famous match"),
        FamousPattern(name: "Khloé Kardashian", western: .cancer, chinese: .rat, line: "Exact famous match"),
        FamousPattern(name: "Liv Tyler", western: .cancer, chinese: .snake, line: "Exact famous match"),

        FamousPattern(name: "Jennifer Lopez", western: .leo, chinese: .rooster, line: "Exact famous match"),
        FamousPattern(name: "Madonna", western: .leo, chinese: .dog, line: "Exact famous match"),
        FamousPattern(name: "Barack Obama", western: .leo, chinese: .ox, line: "Exact famous match"),
        FamousPattern(name: "Kylie Jenner", western: .leo, chinese: .ox, line: "Exact famous match"),
        FamousPattern(name: "Shawn Mendes", western: .leo, chinese: .tiger, line: "Exact famous match"),
        FamousPattern(name: "Demi Lovato", western: .leo, chinese: .monkey, line: "Exact famous match"),
        FamousPattern(name: "Jason Momoa", western: .leo, chinese: .goat, line: "Exact famous match"),
        FamousPattern(name: "Ben Affleck", western: .leo, chinese: .rat, line: "Exact famous match"),

        FamousPattern(name: "Beyoncé", western: .virgo, chinese: .rooster, line: "Exact famous match"),
        FamousPattern(name: "Zendaya", western: .virgo, chinese: .rat, line: "Exact famous match"),
        FamousPattern(name: "Michael Jackson", western: .virgo, chinese: .dog, line: "Exact famous match"),
        FamousPattern(name: "Keanu Reeves", western: .virgo, chinese: .dragon, line: "Exact famous match"),
        FamousPattern(name: "Adam Sandler", western: .virgo, chinese: .horse, line: "Exact famous match"),
        FamousPattern(name: "Salma Hayek", western: .virgo, chinese: .horse, line: "Exact famous match"),
        FamousPattern(name: "Nick Jonas", western: .virgo, chinese: .monkey, line: "Exact famous match"),
        FamousPattern(name: "Amy Winehouse", western: .virgo, chinese: .pig, line: "Exact famous match"),

        FamousPattern(name: "Kim Kardashian", western: .libra, chinese: .monkey, line: "Exact famous match"),
        FamousPattern(name: "Bruno Mars", western: .libra, chinese: .ox, line: "Exact famous match"),
        FamousPattern(name: "Serena Williams", western: .libra, chinese: .rooster, line: "Exact famous match"),
        FamousPattern(name: "Will Smith", western: .libra, chinese: .monkey, line: "Exact famous match"),
        FamousPattern(name: "Gwen Stefani", western: .libra, chinese: .rooster, line: "Exact famous match"),
        FamousPattern(name: "A$AP Rocky", western: .libra, chinese: .dragon, line: "Exact famous match"),
        FamousPattern(name: "Eminem", western: .libra, chinese: .rat, line: "Exact famous match"),
        FamousPattern(name: "Cardi B", western: .libra, chinese: .monkey, line: "Exact famous match"),

        FamousPattern(name: "Drake", western: .scorpio, chinese: .tiger, line: "Exact famous match"),
        FamousPattern(name: "Leonardo DiCaprio", western: .scorpio, chinese: .tiger, line: "Exact famous match"),
        FamousPattern(name: "Katy Perry", western: .scorpio, chinese: .rat, line: "Exact famous match"),
        FamousPattern(name: "Ryan Reynolds", western: .scorpio, chinese: .dragon, line: "Exact famous match"),
        FamousPattern(name: "Kendall Jenner", western: .scorpio, chinese: .pig, line: "Exact famous match"),
        FamousPattern(name: "Anne Hathaway", western: .scorpio, chinese: .dog, line: "Exact famous match"),
        FamousPattern(name: "Jodie Foster", western: .scorpio, chinese: .tiger, line: "Exact famous match"),
        FamousPattern(name: "Julia Roberts", western: .scorpio, chinese: .goat, line: "Exact famous match"),

        FamousPattern(name: "Taylor Swift", western: .sagittarius, chinese: .snake, line: "Exact famous match"),
        FamousPattern(name: "Billie Eilish", western: .sagittarius, chinese: .snake, line: "Exact famous match"),
        FamousPattern(name: "Miley Cyrus", western: .sagittarius, chinese: .monkey, line: "Exact famous match"),
        FamousPattern(name: "Jay-Z", western: .sagittarius, chinese: .rooster, line: "Exact famous match"),
        FamousPattern(name: "Chrissy Teigen", western: .sagittarius, chinese: .ox, line: "Exact famous match"),
        FamousPattern(name: "Britney Spears", western: .sagittarius, chinese: .rooster, line: "Exact famous match"),
        FamousPattern(name: "Nicki Minaj", western: .sagittarius, chinese: .dog, line: "Exact famous match"),
        FamousPattern(name: "Scarlett Johansson", western: .sagittarius, chinese: .rat, line: "Exact famous match"),

        FamousPattern(name: "LeBron James", western: .capricorn, chinese: .rat, line: "Exact famous match"),
        FamousPattern(name: "Timothée Chalamet", western: .capricorn, chinese: .pig, line: "Exact famous match"),
        FamousPattern(name: "Kate Middleton", western: .capricorn, chinese: .rooster, line: "Exact famous match"),
        FamousPattern(name: "Bradley Cooper", western: .capricorn, chinese: .tiger, line: "Exact famous match"),
        FamousPattern(name: "Zooey Deschanel", western: .capricorn, chinese: .goat, line: "Exact famous match"),
        FamousPattern(name: "Dolly Parton", western: .capricorn, chinese: .rooster, line: "Exact famous match"),
        FamousPattern(name: "Mary J. Blige", western: .capricorn, chinese: .pig, line: "Exact famous match"),
        FamousPattern(name: "Diane Keaton", western: .capricorn, chinese: .dog, line: "Exact famous match"),

        FamousPattern(name: "Megan Thee Stallion", western: .aquarius, chinese: .pig, line: "Exact famous match"),
        FamousPattern(name: "Jennifer Aniston", western: .aquarius, chinese: .monkey, line: "Exact famous match"),
        FamousPattern(name: "Harry Styles", western: .aquarius, chinese: .rooster, line: "Exact famous match"),
        FamousPattern(name: "The Weeknd", western: .aquarius, chinese: .horse, line: "Exact famous match"),
        FamousPattern(name: "Oprah Winfrey", western: .aquarius, chinese: .snake, line: "Exact famous match"),
        FamousPattern(name: "Ed Sheeran", western: .aquarius, chinese: .goat, line: "Exact famous match"),
        FamousPattern(name: "Shakira", western: .aquarius, chinese: .snake, line: "Exact famous match"),
        FamousPattern(name: "Michael B. Jordan", western: .aquarius, chinese: .rabbit, line: "Exact famous match"),

        FamousPattern(name: "Rihanna", western: .pisces, chinese: .dragon, line: "Exact famous match"),
        FamousPattern(name: "Justin Bieber", western: .pisces, chinese: .dog, line: "Exact famous match"),
        FamousPattern(name: "Bad Bunny", western: .pisces, chinese: .dog, line: "Exact famous match"),
        FamousPattern(name: "Oscar Isaac", western: .pisces, chinese: .goat, line: "Exact famous match"),
        FamousPattern(name: "Adam Levine", western: .pisces, chinese: .goat, line: "Exact famous match"),
        FamousPattern(name: "Olivia Rodrigo", western: .pisces, chinese: .goat, line: "Exact famous match"),
        FamousPattern(name: "Drew Barrymore", western: .pisces, chinese: .rabbit, line: "Exact famous match"),
        FamousPattern(name: "Liza Minnelli", western: .pisces, chinese: .dog, line: "Exact famous match")
    ]
}
