import { SECTION_KEYS } from "./types.ts";

const stringArray = { type: "array", items: { type: "string" }, minItems: 2 };

export const reasoningSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "sign_pair",
    "central_paradox",
    "western_contribution",
    "chinese_contribution",
    "emergent_identity",
    "what_they_notice",
    "decision_process",
    "trust_process",
    "recurring_misunderstanding",
    "core_need",
    "strength_in_balance",
    "strength_overextended",
    "restoration_pattern",
    "love_pattern",
    "work_pattern",
    "recurring_themes",
    "identity_rhythm",
    "one_sentence_identity_thesis",
    "central_behavioral_proof",
    "plain_language_guardrails",
    "section_plans",
  ],
  properties: {
    sign_pair: { type: "string" },
    central_paradox: { type: "string" },
    western_contribution: { type: "string" },
    chinese_contribution: { type: "string" },
    emergent_identity: { type: "string" },
    what_they_notice: stringArray,
    decision_process: { type: "string" },
    trust_process: { type: "string" },
    recurring_misunderstanding: { type: "string" },
    core_need: { type: "string" },
    strength_in_balance: { type: "string" },
    strength_overextended: { type: "string" },
    restoration_pattern: { type: "string" },
    love_pattern: { type: "string" },
    work_pattern: { type: "string" },
    recurring_themes: {
      type: "array",
      items: { type: "string" },
      minItems: 3,
      maxItems: 5,
    },
    identity_rhythm: { type: "string" },
    one_sentence_identity_thesis: { type: "string" },
    central_behavioral_proof: { type: "string" },
    plain_language_guardrails: {
      type: "array",
      items: { type: "string" },
      minItems: 3,
      maxItems: 6,
    },
    section_plans: {
      type: "array",
      minItems: 7,
      maxItems: 7,
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "section",
          "question",
          "plain_language_thesis",
          "new_insight",
          "behavioral_evidence",
          "signature_detail",
          "themes_to_develop",
          "themes_to_avoid_repeating",
          "idea_to_leave_out",
          "desired_rhythm",
        ],
        properties: {
          section: { type: "string", enum: [...SECTION_KEYS] },
          question: { type: "string" },
          plain_language_thesis: { type: "string" },
          new_insight: { type: "string" },
          behavioral_evidence: stringArray,
          signature_detail: { type: "string" },
          themes_to_develop: stringArray,
          themes_to_avoid_repeating: {
            type: "array",
            items: { type: "string" },
          },
          idea_to_leave_out: { type: "string" },
          desired_rhythm: { type: "string" },
        },
      },
    },
  },
} as const;

export const writingSchema = {
  type: "object",
  additionalProperties: false,
  required: [...SECTION_KEYS],
  properties: Object.fromEntries(
    SECTION_KEYS.map((key) => [key, { type: "string" }]),
  ),
} as const;
