/** Provider-free revalidation overlay for the frozen v5 Run 2 cohort. */
import { auditV5_1CohortRepetition } from "./v5_1_cohort_repetition_audit.ts";
import { V5_VALIDATOR_CORRECTION_V1, validateV5CandidateOutputCorrectionV1 } from "./v5_writer_candidate_validator_correction_v1.ts";

const root = new URL("./", import.meta.url);
const artifacts = new URL("artifacts/", root);
const run2Path = new URL("development-frozen-v5-writer-16-case-cohort-v1-run-2/raw-output-and-qa.json", artifacts);
const v5PreflightPath = new URL("production-candidate-v1-frozen-v5-writer-preflight-v4.json", artifacts);
const correctionPath = new URL("v5_writer_candidate_validator_correction_v1.ts", root);
const auditPath = new URL("v5_1_cohort_repetition_audit.ts", root);
const writerPath = new URL("../canonical-lens-production-preview/one_paragraph_writer_v5_candidate.ts", root);
const revalidationPath = new URL("development-frozen-v5-writer-16-case-cohort-v1-run-2-validator-correction-v5-1-rev-2.json", artifacts);
const revalidationMarkdownPath = new URL("development-frozen-v5-writer-16-case-cohort-v1-run-2-validator-correction-v5-1-rev-2.md", artifacts);
const preflightPath = new URL("production-candidate-v1-frozen-v5-1-one-shot-preflight-v3.json", artifacts);
const preflightMarkdownPath = new URL("production-candidate-v1-frozen-v5-1-one-shot-preflight-v3.md", artifacts);
export const V5_1_PREFLIGHT_VERSION = "pcv1-frozen-v5-1-one-shot-preflight-v3" as const;
const FROZEN_V5_RUN2_ARTIFACT_SHA256 = "102d0b322ab3cb5dc4d2feb7c5896a00ca68df75cfa79e777a40e3401bb5fba9" as const;

function assert(value: unknown, message: string): asserts value { if (!value) throw new Error(message); }
function stable(value: unknown) { return JSON.stringify(value, null, 2) + "\n"; }
async function sha256(value: string) { const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); return Array.from(new Uint8Array(digest)).map((item) => item.toString(16).padStart(2, "0")).join(""); }
async function writeFrozen(path: URL, value: string) { try { const current = await Deno.readTextFile(path); assert(current === value, `Frozen artifact differs: ${path.pathname}`); } catch (error) { if (error instanceof Deno.errors.NotFound) await Deno.writeTextFile(path, value); else throw error; } }

const [run2Text, v5PreflightText, correctionText, auditText, writerText] = await Promise.all([Deno.readTextFile(run2Path), Deno.readTextFile(v5PreflightPath), Deno.readTextFile(correctionPath), Deno.readTextFile(auditPath), Deno.readTextFile(writerPath)]);
const run2 = JSON.parse(run2Text) as any; const v5Preflight = JSON.parse(v5PreflightText) as any;
const frozenV5Run2Sha256 = await sha256(run2Text);
assert(frozenV5Run2Sha256 === FROZEN_V5_RUN2_ARTIFACT_SHA256, "Frozen v5 Run 2 artifact changed; refusing to revalidate or prepare a rerun.");
assert(run2.cases.length === 16, "Frozen v5 Run 2 must have exactly sixteen cases.");
const cases: Array<Record<string, any>> = run2.cases.map((item: any) => {
  const input = { plainInsight: item.writer_input.plain_insight, approvedSecondBeat: item.writer_input.approved_second_beat, approvedInterpersonalEffects: item.writer_input.approved_interpersonal_effects, completenessOutcome: item.completeness_outcome } as const;
  const corrected = validateV5CandidateOutputCorrectionV1(item.parsed_output, input);
  return { stable_reasoning_record_id: item.stable_reasoning_record_id, original_result: item.result, original_errors: item.validation.errors, corrected_result: corrected.accepted ? "PASS" : "FAIL", corrected_errors: corrected.errors, correction_applied: corrected.correction_applied, first_beat_preserved: corrected.first_beat_errors?.length === 0, second_beat_preserved: corrected.second_beat_errors?.length === 0, interpersonal_errors: corrected.interpersonal_inference_errors ?? [], other_person_need_errors: corrected.other_person_need_errors };
});
const refinedAudit = auditV5_1CohortRepetition(run2.cases.map((item: any) => ({ stableCaseId: item.stable_reasoning_record_id, completenessOutcome: item.completeness_outcome, output: item.parsed_output })));
const changed = cases.filter((item: any) => item.original_result !== item.corrected_result);
const revalidation = { version: V5_VALIDATOR_CORRECTION_V1, purpose: "Provider-free overlay. It does not modify frozen v5 Run 2 outputs, prompts, provider metadata, or artifacts.", source_run2_artifact: run2Path.pathname, source_run2_sha256: frozenV5Run2Sha256, source_case_count: run2.cases.length, original_validator_passes: run2.metrics.validator_passes, corrected_validator_passes: cases.filter((item: any) => item.corrected_result === "PASS").length, cases, changed_dispositions: changed, refined_repetition_audit: refinedAudit, providerCalls: 0, writerCalls: 0, copyPersistenceCalls: 0, productionWritePaths: [], shadowWritePaths: [], rolloutChanges: [], deploymentChanges: [], scheduleChanges: [], allowlistChanges: [] };
assert(changed.length === 1 && changed[0].stable_reasoning_record_id === "pcv1-erx-v1-pisces-ox-conflict" && changed[0].corrected_result === "PASS", "Only the approved Pisces × Ox descriptive-need false positive may change.");
assert(cases.every((item: any) => item.first_beat_preserved && item.second_beat_preserved), "v5.1 must retain all approved beats.");
const preflight = { version: V5_1_PREFLIGHT_VERSION, developmentOnly: true, target_project_ref: run2.target_project_ref, approved_model: run2.approved_model, purpose: "Proposed one-shot v5.1 writer rerun. Provider-free preparation only.", proposed_allowlist: v5Preflight.proposed_one_shot_v5_rerun_allowlist, execution_preconditions_for_a_future_provider_run: { OPENAI_API_KEY: "must be present; deliberately not inspected during this provider-free task", OPENAI_IDENTITY_LENS_MODEL: run2.approved_model, development_project_ref: run2.target_project_ref, sequential_provider_calls: 16, automatic_retries: 0, regeneration: false, resume: false }, checks: { same_exact_16_allowlist: v5Preflight.proposed_one_shot_v5_rerun_allowlist.length === 16 && JSON.stringify(v5Preflight.proposed_one_shot_v5_rerun_allowlist) === JSON.stringify(run2.frozen_allowlist), frozen_v5_run2_unchanged: frozenV5Run2Sha256 === FROZEN_V5_RUN2_ARTIFACT_SHA256, v5_writer_source_unchanged: await sha256(writerText) === run2.checks.v5_writer_source_sha256, v5_1_validator_correction_present: Boolean(V5_VALIDATOR_CORRECTION_V1), v5_1_repetition_audit_present: Boolean(refinedAudit.version), no_provider_or_persistence_rollout_deployment_schedule_or_allowlist_paths: [] }, source_hashes: { frozen_v5_run2_sha256: revalidation.source_run2_sha256, v5_writer_source_sha256: await sha256(writerText), v5_1_validator_correction_sha256: await sha256(correctionText), v5_1_repetition_audit_sha256: await sha256(auditText) }, providerCalls: 0, writerCalls: 0, copyPersistenceCalls: 0, productionWritePaths: [], shadowWritePaths: [], rolloutChanges: [], deploymentChanges: [], scheduleChanges: [], allowlistChanges: [] };
assert(Object.values(preflight.checks).every((value) => Array.isArray(value) ? value.length === 0 : value === true), "v5.1 one-shot preflight failed.");
const revalidationMarkdown = `# Frozen v5 Run 2 — Validator Correction v5.1\n\n**Result:** PASS — provider-free revalidation only.\n\n- Original / corrected validator passes: ${revalidation.original_validator_passes} / ${revalidation.corrected_validator_passes}\n- Changed disposition: ${changed.map((item) => item.stable_reasoning_record_id).join(", ")}\n- Provider, writer, persistence, rollout, deployment, schedule, and allowlist changes: 0\n- Mechanical sentence mapping remains an audit signal only: ${refinedAudit.mechanical_sentence_mapping}\n`;
const preflightMarkdown = `# Frozen v5.1 One-Shot Rerun Preflight\n\n**Result:** PASS — proposed rerun only; no provider call.\n\n- Same frozen allowlist: ${preflight.proposed_allowlist.length} records\n- v5 Run 2 preserved: ${preflight.checks.frozen_v5_run2_unchanged}\n- v5 writer unchanged: ${preflight.checks.v5_writer_source_unchanged}\n- v5.1 validator and audit overlays present: ${preflight.checks.v5_1_validator_correction_present} / ${preflight.checks.v5_1_repetition_audit_present}\n- Future provider-run constraints: exactly 16 sequential calls; no retry, regeneration, or resume\n`;
await Promise.all([writeFrozen(revalidationPath, stable(revalidation)), writeFrozen(revalidationMarkdownPath, revalidationMarkdown), writeFrozen(preflightPath, stable(preflight)), writeFrozen(preflightMarkdownPath, preflightMarkdown)]);
console.log(JSON.stringify({ result: "PASS", revalidation_json: revalidationPath.pathname, revalidation_markdown: revalidationMarkdownPath.pathname, v5_1_preflight_json: preflightPath.pathname, v5_1_preflight_markdown: preflightMarkdownPath.pathname, changed_dispositions: changed, providerCalls: 0, writerCalls: 0, productionWritePaths: [], shadowWritePaths: [], rolloutChanges: [], deploymentChanges: [] }, null, 2));
